### ISSUE TITLE
Build break after VS updates .NET SDK and rebuild without restore

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#10019]
VS updated .NET SDK from 6.0.28 to 6.0.29, and a build (without clean or restore) started failing with:

```
C:\Program Files\dotnet\sdk\6.0.420\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(358,5): error MSB4018: The "ResolveTargetingPackAssets" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\6.0.28\data\FrameworkList.xml'.
File name: 'C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\6.0.28\data\FrameworkList.xml'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.AddItemsFromFrameworkList(FrameworkListDefinition definition, IBuildEngine4 buildEngine4, List`1 referenceItems, List`1 analyzerItems)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.Resolve(StronglyTypedInputs inputs, IBuildEngine4 buildEngine)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [Q:\Repos\foo\foo.csproj]
```

This is difficult to investigate, I wish we had better diagnostics for this case.

Binlog available upon request.

**Comment by KirillOsenkov** [comment]
msbuild10019.binlog

**Comment by KirillOsenkov** [comment]
This is because building with SDK 6.0.420, which has LatestRuntimeFrameworkVersion="6.0.28", whereas on disk we have `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.29`

**Comment by KirillOsenkov** [comment]
@dsplaisted any thoughts? It seems that the Microsoft.NetCore.App.Ref has updated to 6.0.29 (there are still some leftover empty folders on disk in 6.0.28), the SDK available is 6.0.420. How can it be?
