### ISSUE TITLE
Got 'Insufficient system resources exist to complete the requested service' while building Store version of application

### ISSUE THREAD

**Issue by 0xNima** [dotnet/msbuild#10162]
### Issue Description

Hello folks, When I tried to build the Store (MSIX) version of [Telegram Desktop](https://github.com/telegramdesktop/tdesktop) application in VS 2022, my build failed with the following logs:

```
1>Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\....\Temp\MSBuildTemp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.

1>C:\....\Temp\MSBuildTemp\MSBuild_pid-18684_d6ae519576884d319a97c37f0006ed4e.failure.txt:1>UNHANDLED EXCEPTIONS FROM PROCESS 18684:

1>=====================

1>5/20/2024 7:22:27 PM

1>System.IO.IOException: Insufficient system resources exist to complete the requested service.

1>

1>   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

1>   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)

1>   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)

1>   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)

1>===================

1>

1>

1>C:\Users\...\Temp\MSBuildTemp\MSBuild_pid-28480_31fcd563a2c9411192e8b7de35718108.failure.txt:

1>UNHANDLED EXCEPTIONS FROM PROCESS 28480:

1>=====================

1>5/20/2024 7:22:26 PM

1>System.IO.IOException: Insufficient system resources exist to complete the requested service.

1>

1>   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

1>   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)

1>   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)

1>   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)

1>===================
....
```

### Steps to Reproduce

1- install and build the solution according to [instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md)

2- Add a new `Windows Application Packaging Project` to the solution named **store-release** and config package name, icons, and etc.

3- Right Click on **store-release** and select **Publish -> Create App Packages...**

4- set **Version**, **Architecture** (x64), and **Solution Configuration** (Release x64) 

5- click on **Create** button

### Actual Behavior

UNHANDLED EXCEPTIONS FROM PROCESS 18684:

```
=====================
5/20/2024 7:22:27 PM
System.IO.IOException: Insufficient system resources exist to complete the requested service.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```

### Analysis

I'm not sure if this problem is merely related to resources, because CPU and RAM usage never hit the limits. I tried to stop some `Event Trace Sessions` in the `Performance Monitoring` window but it didn't help.

Note that I can build the solution successfully from **Build -> Build Solution**. The problem occurs when I try to build the app from  **Publish -> Create App Packages...**.

### Versions & Configurations

the output of `msbuild -version`:
MSBuild version 17.9.8+b34f75857 for .NET Framework 
17.9.8.16306

Machine's configurations:
Processor: 13th Gen Intel(R) Core(TM) i7-13650HX 2.60 GHz - 14 cores, 20 logical processors RAM: 32.0 GB
OS: Windows 11 Home

**Comment by JanKrivanek** [comment]
@0xNima can you try adding `-m:1` if it helps workaround the issue?

**Comment by JanKrivanek** [comment]
@JaynieBai - let's try to repro in VS build with the repo given by customer

**Comment by JaynieBai** [comment]
Repro that and get the following binlog

[CentralNode_devenv_PID=8416_x64_BuildManager_Default_0.binlog.txt](https://github.com/user-attachments/files/16595488/CentralNode_devenv_PID.8416_x64_BuildManager_Default_0.binlog.txt)



![Image](https://github.com/user-attachments/assets/0778b3c4-605c-4212-ac2e-cae7192a3176)

**Comment by 0xNima** [comment]
> @0xNima can you try adding `-m:1` if it helps workaround the issue?

Is it possible to pass this switch from Visual Studio? Because I don't build the solution from the command line. I added `Windows Application Packaging Project` to the solution and set the required fields through `Package.appxmanifest`.

**Comment by JanKrivanek** [comment]
> > @0xNima can you try adding `-m:1` if it helps workaround the issue?
> 
> Is it possible to pass this switch from Visual Studio? Because I don't build the solution from the command line. I added `Windows Application Packaging Project` to the solution and set the required fields through `Package.appxmanifest`.

Yes - set the following to 1:

![image](https://github.com/user-attachments/assets/999eb27f-cc45-4763-8349-710903a7f5eb)

**Comment by 0xNima** [comment]
> > > @0xNima can you try adding `-m:1` if it helps workaround the issue?
> > 
> > 
> > Is it possible to pass this switch from Visual Studio? Because I don't build the solution from the command line. I added `Windows Application Packaging Project` to the solution and set the required fields through `Package.appxmanifest`.
> 
> Yes - set the following to 1:
> 
> ![image](https://private-user-images.githubusercontent.com/3809076/357903748-999eb27f-cc45-4763-8349-710903a7f5eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTQ1MTMsIm5iZiI6MTcyMzc1NDIxMywicGF0aCI6Ii8zODA5MDc2LzM1NzkwMzc0OC05OTllYjI3Zi1jYzQ1LTQ3NjMtODM0OS03MTA5MDNhN2Y1ZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMjAzNjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzEwODAyNDc4ZjI1MGVlOTQwZjI1NDA4Y2UzNDUzZTQ5YzU1MDYwNTU3OWU1ODZiMDBlZDI3YTgwZGE5YjQ5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hZs_Uh2287towuV3peG1mrOx2_-yBXJH_wcGh8LsdOQ)

It works like a charm. It was set to 20 processors. Thank you, Jan

**Comment by JanKrivanek** [comment]
Thanks @0xNima for confirming. By defult it uses number of available logical processors. In some specific cases it can stress the resources, but normally it should increase throughput of your build - so I'd suggest changing it back for other builds.

In any case we should still followup internally on the reason for this (@JaynieBai is looking into collecting memory analysis)

**Comment by JaynieBai** [comment]
It's being internally investigated by the C++ team with ticket https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2317443

**Comment by JaynieBai** [comment]
The C++ team provided the following feedback
_Apprently, cl ran out of memory. The project is pretty big, so you might not have enough memory on the machine to build it with the specified options. Try using MMT [Improve Parallelism in MSBuild - C++ Team Blog](https://devblogs.microsoft.com/cppblog/improved-parallelism-in-msbuild/)._

**Comment by JaynieBai** [comment]
Close it since it's not msbuild issue
