### ISSUE TITLE
[Bug]: ProjectCollection LoadProject throws null reference exception.

### ISSUE THREAD

**Issue by hknielsen** [dotnet/msbuild#10320]
### Issue Description

We have multiple ProjectCollections, one pr project graph that we want Build. The ProjectCollection is kept alive between multiple Build invocations to benefit its caching logic.
We recently ran into problems of the `projectcollection.LoadProject` throwing null reference exceptions on already loaded projects:

```
Object reference not set to an instance of an object.
StackTrace:
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, IDirectoryCacheFactory directoryCacheFactory, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)

   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)

   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)

   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, Boolean interactive)

   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory, Boolean interactive)

   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
```

It does not happen all the time, only some times.
The flow of the application is:

- ProjectCollection is created with GlobalProperties that do not change for its lifetime.
- `LoadProject` is called to evaluate Items/Props.
- BuildManager is invoked to "Restore" with a ForwardLogger, including the same ProjectCollection and its GlobalProperties
- BuildManager is invoked to "Publish" with additional GlobalProperties and ForwardLogger, including the same ProjectCollection and its GlobalProperties
- ProjectCollection is used again to gather some extra information with `LoadProject`
- Sometimes we get the above exception.

The error happens here
https://github.com/dotnet/msbuild/blob/main/src/Build/Evaluation/Evaluator.cs#L316
And is because the `loggingService` is null, and looking at the code that can happen, and it depends on who created the project with `ProjectLoadSettings`.

### Steps to Reproduce

Im not totally sure of the exact flow of when we get into a state in the ProjectCollection that gives this exception, but reevaluation should never throw and looking at the code that could easily happen.

### Expected Behavior

LoadProject should never throw null reference exception when project is reevaluated

### Actual Behavior

Sometimes we get null reference exception in code that should ever throw.

**Comment by hknielsen** [comment]
Mentioning this bug, together with Documentation task, as it could be bad usage of ProjectCollection https://github.com/dotnet/msbuild/issues/9417

**Comment by hknielsen** [comment]
@JanKrivanek @MichalPavlik  We are running into this error again in another place. Going to entirely stop relying on ProjectCollection.Load.
Any estimate on it?

**Comment by MichalPavlik** [comment]
@hknielsen, I'm sorry for the delay. Could you please provide a minimal repro sample? It would speed up our investigation.

@AR-May, was this issue triaged? :) If not, please add it to the list.

**Comment by JanKrivanek** [comment]
@hknielsen Is it possible that you are reusing ProjectCollection after it was Disposed or after getting exception during construction?

Those are the only two cases where the LoggingService initialized in ProjectCollection ctor is nullified.

**Comment by hknielsen** [comment]
@JanKrivanek - Could be.
Just to clarify;
We have x amount of Instances of ProjectCollection.
Each invocation of the BuildManager get passed one of these ProjectCollections matching the Project we are going to build.

We can call Dispose on One of the `ProjectCollection` at some point, while the others live on.
So what you are saying, that should work?

Im going to investigate if we could have called Dispose on the ProjectCollection thats failing

**Comment by hknielsen** [comment]
@JanKrivanek Confirmed that it was disposed and we continued to use it afterwords. I agree on the proposal in https://github.com/dotnet/msbuild/issues/10648

**Comment by MichalPavlik** [comment]
Thanks @hknielsen for confirmation. I will close this issue and the team will plan my proposal next week.
