### ISSUE TITLE
[Bug]: FileMatcherTest.Unc test fails on macOS

### ISSUE THREAD

**Issue by jrdodds** [dotnet/msbuild#10716]
### Issue Description

When I build locally and run tests on macOS 14 on ARM and macOS 13 on Intel, the `Microsoft.Build.UnitTests.FileMatcherTest.Unc` test fails.

### Steps to Reproduce

After confirming local repo is up to date:
1. Run `./build.sh`
1. Run `./build.sh --test`

### Expected Behavior

All tests should pass.

### Actual Behavior

The `Microsoft.Build.UnitTests.FileMatcherTest.Unc` test fails:

```
Failed tests
Microsoft.Build.UnitTests.FileMatcherTest.Unc
Assert.Equal() Failure: Values differ\nExpected: 1\nActual:   0
   at Microsoft.Build.UnitTests.FileMatcherTest.MatchDriver(String filespec, String[] excludeFilespecs, String[] matchingFiles, String[] nonmatchingFiles, String[] untouchableFiles, Boolean normalizeAllPaths, Boolean normalizeExpectedMatchingFiles) in /Users/jrdodds/Projects/jrdodds/msbuild/src/Shared/UnitTests/FileMatcher_Tests.cs:line 2426
   at Microsoft.Build.UnitTests.FileMatcherTest.MatchDriver(String filespec, String[] matchingFiles, String[] nonmatchingFiles, String[] untouchableFiles) in /Users/jrdodds/Projects/jrdodds/msbuild/src/Shared/UnitTests/FileMatcher_Tests.cs:line 2362
   at Microsoft.Build.UnitTests.FileMatcherTest.ValidateFileMatch(String filespec, String fileToMatch, Boolean shouldBeRecursive, Boolean fileSystemSimulation) in /Users/jrdodds/Projects/jrdodds/msbuild/src/Shared/UnitTests/FileMatcher_Tests.cs:line 2533
   at Microsoft.Build.UnitTests.FileMatcherTest.ValidateFileMatch(String filespec, String fileToMatch, Boolean shouldBeRecursive) in /Users/jrdodds/Projects/jrdodds/msbuild/src/Shared/UnitTests/FileMatcher_Tests.cs:line 2512
   at Microsoft.Build.UnitTests.FileMatcherTest.Unc() in /Users/jrdodds/Projects/jrdodds/msbuild/src/Shared/UnitTests/FileMatcher_Tests.cs:line 1114
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

The following files are attached in a .zip file.

- Microsoft.Build.Engine.UnitTests_net9.0_x64.html
- Microsoft.Build.Engine.UnitTests_net9.0_x64.xml

[Build.Engine.UnitTests_net9.0_x64.zip](https://github.com/user-attachments/files/17171653/Build.Engine.UnitTests_net9.0_x64.zip)

### Analysis

I successfully ran the tests on August 5, 2024 so it would seem that something changed after that point.

### Versions & Configurations

macOS Sonoma 14.6.1
Apple M1 Pro (ARM)

macOS Ventura 13.6.9
Intel Core i7

**Comment by surayya-MS** [comment]
I tried to run this test on Apple M2 Pro macOs 15.4.1 and it fails.

**Comment by surayya-MS** [comment]
The tests now passes. Haven't changed anything except pulled changes from main branch.

**Comment by jrdodds** [comment]
> there is also a possibility that [macOS] started behaving differently during this time

 If it's true that macOS behavior changed, then both macOS 13 and macOS 14 changed. That would suggest something in the August 7, 2024 security updates macOS Ventura 13.6.9 and macOS Sonoma 14.6.1 and/or the September 16, 2024 security updates [macOS Ventura 13.7](https://support.apple.com/en-us/121234) and [macOS Sonoma 14.7](https://support.apple.com/en-us/121247).
