### ISSUE TITLE
Internal MSBuild Error during logging by AssemblyLoadsTracker

### ISSUE THREAD

**Issue by danmoseley** [dotnet/msbuild#11095]
### Issue Description

This is with 10.0.100-alpha.1.24573.1
Build log while it lasts https://[dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/887239/logs/226](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/887239/logs/226)

I thought this might be a task bug similar to the Restore task bug that caused https://github.com/dotnet/msbuild/issues/4792. Then wondered, how I could make it log which task was logging. Then realized the logging seems to be from within "AssemblyLoadsTracker" not a task.

```
Build FAILED.

MSBUILD : error MSB4166: Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in "/mnt/vss/_work/1/s/artifacts/log/Release" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory. [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: /mnt/vss/_work/1/s/artifacts/log/Release/MSBuild_pid-21939_4a3f1338ba4d49eeb5ba3df414c5b8de.failure.txt: [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 21939: [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: ===================== [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: 12/5/2024 3:07:31 PM [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 1702 should have been in the ID-to-project file mapping but wasn't! [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args) [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: at Microsoft.Build.BackEnd.Logging.LoggingService.GetAndVerifyProjectFileFromContext(BuildEventContext context) [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: at Microsoft.Build.BackEnd.Logging.LoggingService.LogBuildEvent(BuildEventArgs buildEvent) [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args) [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: =================== [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166:  [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166:  [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in "/mnt/vss/_work/1/s/artifacts/log/Release" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory. [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: /mnt/vss/_work/1/s/artifacts/log/Release/MSBuild_pid-21939_4a3f1338ba4d49eeb5ba3df414c5b8de.failure.txt: [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 21939: [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: ===================== [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: 12/5/2024 3:07:31 PM [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 1702 should have been in the ID-to-project file mapping but wasn't! [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args) [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: at Microsoft.Build.BackEnd.Logging.LoggingService.GetAndVerifyProjectFileFromContext(BuildEventContext context) [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: at Microsoft.Build.BackEnd.Logging.LoggingService.LogBuildEvent(BuildEventArgs buildEvent) [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args) [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166: =================== [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166:  [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
MSBUILD : error MSB4166:  [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
EXEC : npm error Lifecycle script `integration-test` failed with error :  [/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj]
/mnt/vss/_work/1/s/eng/Npm.Workspace.FunctionalTests.nodeproj(28,5): error MSB3073: The command "npm run integration-test" exited with code 1.
```

### Steps to Reproduce

Don't know how to repro. Binary log on request, but I think this may start with code inspection

### Expected Behavior

.

### Actual Behavior

.

**Comment by danmoseley** [comment]
This comment is suggestive? 

https://github.com/dotnet/msbuild/commit/9342681ec64ac1519328698179ef843d258116a9#diff-7f217b4ccb76592a2ab78dd7f8332509dfa2e2216d8a6032f956cbdf48df8d03R174

@JanKrivanek

**Comment by danmoseley** [comment]
Minor cleanup around this logging you are welcome to take. https://github.com/dotnet/msbuild/compare/main...danmoseley:msbuild:contextid.msg?expand=1

**Comment by danmoseley** [comment]
Occurs to me: it might be good for this exception message to include the string that would have been logged. Will provide a clue when root causing.

**Comment by YuliiaKovalova** [comment]
It can be the same thing: https://github.com/dotnet/msbuild/issues/10176

**Comment by YuliiaKovalova** [comment]
It fails for sdk too when buildCheck is enabled: https://dev.azure.com/dnceng-public/public/_build/results?buildId=916876&view=logs&jobId=cc0c8ce4-bcb9-5d43-b4e1-7b7d984b2587&j=cc0c8ce4-bcb9-5d43-b4e1-7b7d984b2587&t=41208fa4-d974-5edb-a6e5-02356f49c88e

**Comment by YuliiaKovalova** [comment]
[mapping_error.zip](https://github.com/user-attachments/files/18422948/mapping_error.zip)
@JanKrivanek binlog with the error captured.

**Comment by andrewlock** [comment]
We are building with 9.0.102 and we have seen this same error in CI (I think). Will the fix be backported to the .NET 9 SDK?

```
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTemproot/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166: /tmp/MSBuildTemproot/MSBuild_pid-127_bcfa4fc861024368b28eef4c9ca939c6.failure.txt:
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 127:
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166: =====================
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166: 04/10/2025 10:29:59
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 74 should have been in the ID-to-project file mapping but wasn't!
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166:    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Logging.LoggingService.LogBuildEvent(BuildEventArgs buildEvent)
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args)
[ERR] CompileManagedUnitTe: MSBUILD : error MSB4166: ===================
```

**Comment by danmoseley** [comment]
@JanKrivanek for that q ^^
