### ISSUE TITLE
Worker node crash due to race on BuildRequestConfiguration.ActivelyBuildingTargets

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#1464]
Got a report of an MSBuild crash from the internal Visual Studio build:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at Microsoft.Build.BackEnd.BuildRequestEntry.GetActiveTargets()
   at Microsoft.Build.BackEnd.BuildRequestEngine.IssueUnsubmittedRequests()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass60_0.<Builder_OnBlockedRequest>b__0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass67_0.<QueueAction>b__0()
```

**Comment by rainersigwald** [comment]
I have no idea what's causing the race, but it looks like a lot of the use of that field would be simplified if it were a `ConcurrentDictionary` instead of a plain one.

**Comment by YuliiaKovalova** [comment]
No recent repro, close it for now.
If happens again, we will fill the fresh ticket.
