### ISSUE TITLE
Crash deserializing BuildEventArgs-derived type in logging node

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#1675]
[This was reported by an internal user via email]

Microsoft (R) Build Engine version 15.1.523.56541
This is part of VS 26119.0.d15rel

Getting a repro only takes 2 minutes if you have the C++ tools and Windows 8.1 SDK installed:

Open a "Developer Command Prompt for VS 2017 RC"
1) git clone https://github.com/lz4/lz4.git D:\LZ4\src
2) cd D:\LZ4
3) devenv /upgrade .\src\visual\vs2010\lz4.sln
4) msbuild /p:Configuration=Release;Platform=x64 .\src\visual\VS2010\lz4.sln /t:Rebuild /m /p:BuildInParallel=true

The last command yields a crash in msbuild.exe:

```
Unhandled Exception: System.ArgumentException: Object of type 'Microsoft.VisualStudio.CodeAnalysis.AnalysisResults.AnalysisMessage' cannot be converted to type 'Microsoft.VisualStudio.CodeAnalysis.AnalysisResults.AnalysisMessage'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RtFieldInfo.UnsafeSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Runtime.Serialization.FormatterServices.SerializationSetValue(MemberInfo fi, Object target, Object value)
   at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
   at System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketReadTranslator.TranslateDotNet[T](T& value)
   at Microsoft.Build.Shared.LogMessagePacketBase.ReadFromStream(INodePacketTranslator translator)
   at Microsoft.Build.Shared.LogMessagePacketBase.Translate(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.LogMessagePacket.FactoryForDeserialization(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.PacketFactoryRecord.DeserializeAndRoutePacket(Int32 nodeId, INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodeManager.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.NodeContext.ReadAndRoutePacket(NodePacketType packetType, Byte[] packetData, Int32 packetLength)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.NodeContext.BodyReadComplete(IAsyncResult result)
   at System.IO.Pipes.PipeStream.AsyncPSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by rainersigwald** [comment]
I can repro this on MSBuild 15.1.545.13942, including under a debugger. Investigating.

**Comment by rainersigwald** [comment]
Actually, my repro is very slightly different. The exception I get is

```
System.Runtime.Serialization.SerializationException: Unable to find assembly 'Microsoft.VisualStudio.CodeAnalysis, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Which doesn't seem very true--that assembly (well, version `15.0.26205.0` on my machine) is loaded into the process that claims it can't find it.

**Comment by rainersigwald** [comment]
My current theory is that the original reporter had an incompatible version of `Microsoft.VisualStudio.CodeAnalysis` in the GAC, while I don't have one. That would explain the cast error and my failure to find the assembly.

This is occurring because the `NativeCodeAnalysis` task calls

```C#
CodeAnalysisWarningEventArgs e = ...;
BuildEngine.LogWarningEvent(e);
```

where 

```c#
internal class CodeAnalysisWarningEventArgs : 
        BuildWarningEventArgs,
        ICodeAnalysisEventArgs
```

The worker node attempts to serialize the `BuildWarningEventArgs` across the process boundary to the main logging node, where we fail to deserialize it. That wasn't a problem in dev14 because that assembly was in the GAC so its types were available to any MSBuild.exe that wanted them.

Ideally, MSBuild would be robust to this situation, but it doesn't look like there's an easy way to handle the deserialization error gracefully. I'm following up with an internal bug on the `NativeCodeAnalysis` task to stop using a derived type and instead just log a `BuildWarningEventArgs`.

**Comment by rainersigwald** [comment]
The larger problem of crashing on deserialization of a BuildEventArgs-derived type is still there, so I'm reopening and generalizing this issue.

**Comment by rainersigwald** [comment]
Superseded by #8823.
