### ISSUE TITLE
NullReferenceException in TaskItem.GetMetadataEscaped

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#3193]
This Roslyn CI build has the BinaryLogger crashed while getting metadata from a Task Item:
https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/ubuntu_16_mono_debug_prtest/239/consoleFull#149247994579494335-f7bd-47d0-8771-8661e00c2db2

```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
13:16:19 Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.NullReferenceException: Object reference not set to an instance of an object.
13:16:19    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadataEscaped(String metadataName)
13:16:19    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadata(String metadataName)
13:16:19    at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)
13:16:19    at Microsoft.Build.Logging.BuildEventArgsWriter.WriteItems(IEnumerable items)
13:16:19    at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ProjectStartedEventArgs e)
13:16:19    at Microsoft.Build.Logging.BuildEventArgsWriter.Write(BuildEventArgs e)
13:16:19    at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)
13:16:19    at Microsoft.Build.Logging.BinaryLogger.EventSource_AnyEventRaised(Object sender, BuildEventArgs e)
13:16:19    at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.AnyEventRaisedHandler(Object sender, BuildEventArgs e)
13:16:19    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
```

**Comment by KirillOsenkov** [comment]
From eyeballing http://source.dot.net/#Microsoft.Build/Instance/ProjectItemInstance.cs,ece1baeb960ed0c0 I don't see a location where we could NullRef. 

This may be an OOM condition when the runtime failed to allocate due to OOM and we're dying anyway.

Mainly filing for awareness, in case we see this again.

**Comment by YuliiaKovalova** [comment]
feel free to reopen if it happens again.
