### ISSUE TITLE
Custom property function assembly location

### ISSUE THREAD

**Issue by DoCode** [dotnet/msbuild#4028]
When I will use a property function in a custom assembly, where should I place the assembly that .NET Core and MSBuild will find it?

The static class:
```cs
namespace DotNet.Build.Common
{
    public static class ConfigUtilities
    {
        public static string WriteConfigPropsFile(string filePath)
        {
            return $"Hello from {nameof(ConfigUtilities)}::{nameof(WriteConfigPropsFile)}: {filePath}";
        }
    }
}
```

The default .NET Standard project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <DelaySign>false</DelaySign>
    <AssemblyOriginatorKeyFile>DotNet.Build.Common.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

</Project>
```

Then register the assembly in the GAC:
> Q: Exists a better, portable, location where the assembly can be stored?
```powershell
gacutil.exe -i DotNet.Build.Common.dll
```

## Use the new property function:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Execute">

  <PropertyGroup>
    <_TestVariable>$([DotNet.Build.Common.ConfigUtilities, DotNet.Build.Common, Version=42.42.42.0, Culture=neutral, PublicKeyToken=d6811ab7c1c33a7c]::WriteConfigPropsFile("Hallo"))</_TestVariable>
  </PropertyGroup>

  <Target Name="Execute">
    <Error Text="_TestVariable: $(_TestVariable)" />
  </Target>

</Project>
```

## Execute
```powershell
dotnet.exe build project.proj
and/or
msbuild.exe msbuild project.proj
```

## Result:
```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.IO.FileLoadException: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean raiseResolveEvent)
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.GetTypeFromAssembly(String typeName, String candidateAssemblyName)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.GetTypeFromAssemblyUsingNamespace(String typeName)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.GetTypeForStaticMethod(String typeName, String simpleMethodName)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.ExtractPropertyFunction(String expressionFunction, IElementLocation elementLocation, Object propertyValue, UsedUninitializedProperties usedUnInitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings)
   at Microsoft.Build.BackEnd.RequestBuilder.LoadProjectFromFile()
   at Microsoft.Build.BackEnd.BuildRequestConfiguration.InitializeProject(BuildParameters buildParameters, Func`1 loadProjectFromFile)
   at Microsoft.Build.BackEnd.RequestBuilder.LoadProjectIntoConfiguration()
   at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()
   at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.IO.FileLoadException: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)

Unhandled Exception: System.IO.FileLoadException: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
```

**Comment by DoCode** [comment]
## Update 1
I found, that after the GAC registration the local installed MSBuild (VS developer prompt) instance found the assembly and the property function worked.

**So, the question is, why a `dotnet build` or `dotnet msbuild` doesn't worked!?**

**Comment by DoCode** [comment]
## Update 2
**It worked also when I place the assembly to e.g.`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin` without GAC registration!**

**Comment by DoCode** [comment]
### Update 3 (dotnet.exe msbuild)
So this worked also, when I place the library inside e.g. `C:\Program Files\dotnet\sdk\2.2.101` **AND** add the `SDK` tag on the `Project` attribute:
```xml
<Project SDK="Microsoft.Build.NoTargets/1.0.40" DefaultTargets="Execute">
...
```

**So, what can we do, to deploy this assemblies at a location outside from `C:\Program Files` or `C:\Program Files (x86)` that MSBuild could load it?**

**Comment by rainersigwald** [comment]
Only the [documented property functions](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2017) are supported; there's no (intentional) extensibility mechanism to add your own. Honestly, I consider it a bug that it works for a GACed type with a fully-qualified name.

MSBuild is intended to be extended via custom targets and tasks. Can you convert this code to be a task instead?

**Comment by Nirmal4G** [comment]
It's not a bug. It's an actual undocumented feature from .NET Framework 4 days. I remember that I have read it older blog when it was introduced. It was God send. I still have some of the snippets and files from those days.

**Comment by Nirmal4G** [comment]
> So, what can we do, to deploy this assemblies at a location outside from `C:\Program Files` or `C:\Program Files (x86)` that MSBuild could load it?

We could try Custom App/Assembly config for `MSBuild.exe/dll` to check for assemblies in certain locations. But that's still a stretch.
