### ISSUE TITLE
MSB0001: Internal MSBuild Error: Node does not have a provider. 

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#455]
We got a report of an intermittent msbuild failure (~once every 2 weeks) with the following message: 

```
UNHANDLED EXCEPTIONS FROM PROCESS 4544: 
===================== 

Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 2 does not have a provider. 
at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary) 
at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine) 
at Microsoft.Build.CommandLine.MSBuildApp.Main() 
=================== 
```

Context details: 6 C# projects, built on VS2015. The solution is a VS2010 solution with target .net 4.0.

Cmdline (with replaced project names): 
Executing the command cmd.exe /C " "C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe" /t:Clean,Build /P:Configuration=Release;Platform=x86 /maxcpucount ProjectFolder\Project.sln " && exit %%ERRORLEVEL%% from H:\Jenkins\workspace\Dev_Build 
[Dev_Build] $ cmd.exe /C " "C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe" /t:Clean,Build /P:Configuration=Release;Platform=x86 /maxcpucount ProjectFolder\Project.sln " && exit %%ERRORLEVEL%%

**Comment by cdmihai** [comment]
I looked over the code to see how a node can get to have a null provider.
 
It seems possible to get into this state. One would have to:
Shutdown a node (BuildManager.Shutdown())
Send message to that node (BuildManager.PerformActions(), which at some point leads to NodeManager.SendData())
 
I also saw some potential concurrency concerns that might lead to this interleaving:
Escaped node ints: When a node is created, an int token is created as a reference for that node. The node manager just seems to accept these tokens without validation, and I did not find code that invalidates an int node reference. In consequence, it could be possible to have an escaped int token representing a node that was shut down still circulating in the node manager and build manager.
NodeManager._NodesShutdown is not volatile. Are the possible callers confined to the same thread? If not, stale cache values of this boolean could cause missed shutdown messages to node manager. This could lead to messages being passed to nodes after shutdown.
BuildManager._ShuttingDown is not volatile. Same story as above. Accessed without a lock in BuildManager.Reset()
There's use of non thread safe collections (_activeNodes field in BuildManager)

Next steps: 
- see if we can write a unit test invoking the BuildManager with the above steps that exposes this interleaving

**Comment by cdmihai** [comment]
New dump with stack available in internal issue: https://devdiv.visualstudio.com/DevDiv/_workitems?id=229584&_a=edit

Summary of interesting things from the stack:
- There is one inproc node
- Its NodeProviderInProc has the following state:
  - Disposed = true
  - inProcNode = null
  - inProcNodeId = 0
  - inProcNodeEndPoint.ComponentHost (BuildManager)
    - shuttingDown = false
    - disposed = true
    - activeNodes = empty
    - nodeManager = null
    - nodeIdToKnownConfigurations = empty
    - buildManagerState = Idle

BuildManager has shuttingDown = False, nodeManager = null, disposed = true, and buildManagerState = Idle suggests that BuildManager.Reset was called. This only gets call on EndBuild, which looks like it's called from the command line after the build finished.

**Comment by wilstoff** [comment]
We have been getting this same issue intermittently as well.  Any updates? or if it has been fixed in a newer version? 
 **********************************************************************


** Visual Studio 2017 Developer Command Prompt v15.6.4


** Copyright (c) 2017 Microsoft Corporation


**********************************************************************


MSBUILD : error MSB4166: Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.





Build succeeded.


    0 Warning(s)


    1 Error(s)





Time Elapsed 00:00:01.15


MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.


Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 4 does not have a provider.


   at Microsoft.Build.Execution.BuildManager.EndBuild()


   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler)





MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.


Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 4 does not have a provider.


   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler)


   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)






Unhandled Exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 4 does not have a provider.


   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler)


   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)


   at Microsoft.Build.CommandLine.MSBuildApp.Main()

**Comment by cdmihai** [comment]
@wilstoff It hasn't been fixed. Do you have a repro you can zip up and attach here?

**Comment by vok1980** [comment]
Got the same problem:
```
UNHANDLED EXCEPTIONS FROM PROCESS 716:
=====================
1/18/2019 8:28:43 PM
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 2 does not have a provider.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
===================
```
Microsoft Visual Studio Professional 2017 
Version 15.9.4
VisualStudio.15.Release/15.9.4+28307.222

**Comment by vok1980** [comment]
Is there any workaround for it?

**Comment by cdmihai** [comment]
@vok1980 turning off parallel builds would probably fix it. If you have a consistent repro, feel free to share it.

**Comment by rainersigwald** [comment]
> msbuild does not finish process after build immediately

True, when `/nodeReuse:true` (which is the default).

> some collision with next build happens

That shouldn't happen, and doesn't in most cases. If you can narrow down any repro steps, we'd love to know them so we can fix the bug.

**Comment by vok1980** [comment]
Unfortunately, the only thing I can tell you about my project that its rather big. Build time is about 1h40m with 8 cores & 16G mem. And it does not matter if builds are taking place on the same workspace or separate workspaces. Hope, it can help you.

**Comment by williambrode** [comment]
@vok1980 I'm seeing the issue too and haven't tried /nodeReuse:false yet.  But how confident are you that this setting fixes it?  I only ask if it was intermittent and hard to reproduce if you've just gotten lucky so far.

**Comment by vok1980** [comment]
@williambrode It was 100% reproducing in my case. Now its 0% reproducing for a long time in the same case.

**Comment by danmosemsft** [comment]
If your build time is that long, `/nodeReuse:false` would not affect perf measurably. It's an optimization for very quick, probably up to date builds of one or two projects.

If it's in VS, I am not sure whether VS now has a setting to disable node reuse, it used to be accomplished by setting an env var MSBUILDDISABLENODEREUSE=1.

**Comment by vaboca** [comment]
Hi everyone, 
I got a consistent repro when enabling /graph on our root node project (with or without /nr:false)

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 2 does not have a provider.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.BackEnd.NodeManager.SendData(Int32 node, INodePacket packet)
   at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
   at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
   at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 2 does not have a provider.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 2 does not have a provider.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()

**Comment by felixpelletier** [comment]
Still having this issue in 2022. In our case it's when using the command `dotnet restore -p:UseSharedCompilation=false src\Solution.sln`

**Comment by neighbour-oldhuang** [comment]
我也遇到了这个问题 sad。。
UNHANDLED EXCEPTIONS FROM PROCESS 32204:
=====================
2022/9/22 20:42:46
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 5 does not have a provider.
   在 Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
   在 Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   在 Microsoft.Build.CommandLine.MSBuildApp.Main()
===================

我执行的命令：
msbuild.exe -m -t:Rebuild -restore -clp:PerformanceSummary;ErrorsOnly;Summary -flp:LogFile=msbuild.log;Verbosity=normal;PerformanceSummary;ShowTimestamp -p:Configuration=Release;RestorePackagesConfig=true;WarningLevel=1;BuildProjectReferences=true;SolutionDir=n:\jenkins\workspace\Multi-Build-jobv2 n:\jenkins\workspace\Multi-Build-jobv2\S3.IOP.ClientSvr\S3.IOP.ClientSvr.csproj

我的工具版本：
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642

还没有找到它出现的规律

**Comment by pasisavolainen** [comment]
Getting this intermittently. Jenkins, linux builder.
```
[Pipeline] sh (Restoring nuget packages)
+ dotnet restore solution.sln -s http://sourcea/ -s http://sourceb -s http://sourcec
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 2 does not have a provider.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.BackEnd.NodeManager.SendData(Int32 node, INodePacket packet)
   at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
   at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
   at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass76_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
   at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
--- End of stack trace from previous location ---
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 2 does not have a provider.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
Unhandled exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Node 2 does not have a provider.
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
   at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.ExecuteInProc(String[] arguments)
[Pipeline] }
```

**Comment by hknielsen** [comment]
Ok a coworker got a bit more information of what went wrong with the Node for us:
```
UNHANDLED EXCEPTIONS FROM PROCESS 7140:
=====================
7/2/2024 1:15:27 PM
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.
 ---> Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.
 ---> Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project file "xxx.props" could not be loaded. The process cannot access the file 'xxx.props" ' because it is being used by another process.  xxx\Sdk.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, 
```

**Comment by danmoseley** [comment]
@hknielsen I think that's unrelated (unless you're getting the other error as well). I suggest opening another issue. That should not happen.

**Comment by YuliiaKovalova** [comment]
Feel free to reopen if you hit it again.
