### ISSUE TITLE
Re-enable tests that dispose the InProcNodeProvider

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/msbuild#515]
Various tests dispose the `NodeProviderInProc` instance from the global component host in the following fashion:

``` C#
// Since we're creating our own BuildManager, we need to make sure that the default 
// one has properly relinquished the inproc node
NodeProviderInProc nodeProviderInProc = ((IBuildComponentHost)BuildManager.DefaultBuildManager).GetComponent(BuildComponentType.InProcNodeProvider) as NodeProviderInProc;
if (nodeProviderInProc != null)
{
    nodeProviderInProc.Dispose();
}
```

This tends to cause failures in other unrelated tests that end up trying to use the disposed instance, generally surfacing as a null reference, for example:

```
         System.NullReferenceException: Object reference not set to an instance of an object.
            at Microsoft.Build.BackEnd.NodeProviderInProc.InProcNodeEndpoint_OnLinkStatusChanged(INodeEndpoint endpoint, LinkStatus status) in c:\git\msbuild\src\XMakeBuildEngine\BackEnd\Components\Communications\NodeProviderInProc.cs:line 417
            at Microsoft.Build.BackEnd.NodeEndpointInProc.RaiseLinkStatusChanged(LinkStatus newStatus) in c:\git\msbuild\src\XMakeBuildEngine\BackEnd\Components\Communications\NodeEndpointInProc.cs:line 261
            at Microsoft.Build.BackEnd.NodeEndpointInProc.ChangeLinkStatus(LinkStatus newStatus) in c:\git\msbuild\src\XMakeBuildEngine\BackEnd\Components\Communications\NodeEndpointInProc.cs:line 319
            at Microsoft.Build.BackEnd.NodeEndpointInProc.SetPeerNodeConnected() in c:\git\msbuild\src\XMakeBuildEngine\BackEnd\Components\Communications\NodeEndpointInProc.cs:line 279
            at Microsoft.Build.BackEnd.NodeEndpointInProc.Listen(INodePacketFactory factory) in c:\git\msbuild\src\XMakeBuildEngine\BackEnd\Components\Communications\NodeEndpointInProc.cs:line 176
            at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException) in c:\git\msbuild\src\XMakeBuildEngine\BackEnd\Node\InProcNode.cs:line 155
```

For now, I am disabling all these tests.  We may want to go back and find a better way to test this behavior or just delete the tests.

Instances of this include:
- `Scheduler_Tests`
- `TargetEntry_Tests.AfterTargetsShouldReportFailedBuild`
- `SolutionProjectGenerator_Tests.BadFrameworkMonkierExpectBuildToFail`
- `SolutionProjectGenerator_Tests.BadFrameworkMonkierExpectBuildToFail2`

**Comment by benbryant0** [comment]
I've been looking into this a little to help with #5604. I'm entirely new to this codebase and have no idea what's changed in the 4.5 years since this issue was created, so I may be missing lots of things, but:

Enabling the 25 tests tagged with this issue doesn't seem to cause any problems in my test runs (running build.cmd and cibuild_bootstrapped_msbuild.ps1), other than one of the currently disabled tests (`SolutionProjectGenerator_Tests.BadFrameworkMonkierExpectBuildToFail2`) now failing due to changes in the method(s) it tests. This looks easy to fix.

I may just be ignorant, but in the codebase as it is now I can't see why these tests should dispose the `DefaultBuildManager`'s `NodeProviderInProc` (in this way, at least) before they are run. Removing this disposal seems to cause no issues. Also:

* As far as I can see, each `BuildManager` instance should have its own `NodeProviderInProc` instance.
* The only obvious thing I can see that may cross between separate instances is the private *static* field `Semaphore InProcNodeOwningOperatingEnvironment`; but this is only used if the environment variable `MSBUILDINPROCENVCHECK` is set, which is only set in 3 test suites which also use `TestEnvironment` to revert this change. As long as these tests don't run in parallel, that seems fine.
* There are several other tests that instantiate their own `BuildManager` without doing this strange disposal. However, those all use `TestEnvironment` which will dispose `DefaultBuildManager` if it has been instantiated. Some of them then also manually dispose it on top of that..

The first two points seem like enough reason to just drop the strange disposal and my local testing indicates that no more is needed. But to be extra safe (and more consistent) we could add `TestEnvironment` instances to these tests as well.

Can someone more familiar say if this sounds reasonable?
