### ISSUE TITLE
NullReferenceException in TaskItem.CloneCustomMetadata

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#5296]
https://dev.azure.com/dnceng/public/_build/results?buildId=606202&view=logs&j=cb341b57-5007-5864-c16a-52e37a0ec5e0&t=c61b4578-f14d-5df9-c7d3-764b6253e0ae&l=719

```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CloneCustomMetadata()
   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)
   at Microsoft.Build.Logging.BuildEventArgsWriter.WriteItems(IEnumerable items)
   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ProjectStartedEventArgs e)
   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(BuildEventArgs e)
   at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)
   at Microsoft.Build.Logging.BinaryLogger.EventSource_AnyEventRaised(Object sender, BuildEventArgs e)
   at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.AnyEventRaisedHandler(Object sender, BuildEventArgs e)
   at Microsoft.Build.Framework.AnyEventHandler.Invoke(Object sender, BuildEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseStatusEvent(Object sender, BuildStatusEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseProjectStartedEvent(Object sender, ProjectStartedEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent, Int32 sinkId)
   at Microsoft.Build.BackEnd.Logging.EventRedirectorToSink.Microsoft.Build.Framework.IEventRedirector.ForwardEvent(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.CentralForwardingLogger.EventSource_AnyEventRaised(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
```

(thanks @Pilchie)

**Comment by rainersigwald** [comment]
Possible other hit:

https://dev.azure.com/dnceng/internal/_build/results?buildId=666725&view=logs&j=ed2c9767-8cce-57f8-db55-61577f1ca8b3&t=18691dd0-6061-5cb2-fba9-a0cfba854e8b&l=4382

```
Build FAILED.

F:\workspace\_work\1\s\.packages\microsoft.dotnet.apicompat\5.0.0-beta.20278.4\build\Microsoft.DotNet.ApiCompat.targets(145,5): error MSB4181: The "Exec" task returned false but did not log an error. [F:\workspace\_work\1\s\src\libraries\System.Security.Cryptography.Algorithms\src\System.Security.Cryptography.Algorithms.csproj]
F:\workspace\_work\1\s\.packages\microsoft.dotnet.apicompat\5.0.0-beta.20278.4\build\Microsoft.DotNet.ApiCompat.targets(145,5): error MSB4181: The "Exec" task returned false but did not log an error. [F:\workspace\_work\1\s\src\libraries\System.Runtime.Serialization.Xml\src\System.Runtime.Serialization.Xml.csproj]
F:\workspace\_work\1\s\.packages\microsoft.net.compilers.toolset\3.7.0-3.20271.4\tasks\netcoreapp3.1\Microsoft.CSharp.Core.targets(59,5): error MSB4181: The "Csc" task returned false but did not log an error. [F:\workspace\_work\1\s\src\libraries\System.Security.Cryptography.Algorithms\src\System.Security.Cryptography.Algorithms.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:14:56.82
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CloneCustomMetadata()
   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)
   at Microsoft.Build.Logging.BuildEventArgsWriter.WriteItems(IEnumerable items)
   at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
```

**Comment by ericstj** [comment]
Just hit this again here.  https://dev.azure.com/dnceng/public/_build/results?buildId=727755&view=logs&j=da3b6fae-2b9c-515e-f961-941b19f305e4&t=e211c71e-116d-5222-99f8-68e08c58ca66

cc @maryamariyan

```
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CloneCustomMetadata()
   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)
   at Microsoft.Build.Logging.BuildEventArgsWriter.WriteItems(IEnumerable items)
   at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
```

**Comment by marcpopMSFT** [comment]
@rainersigwald confirm if your copy on write dictionary changes updated this.

**Comment by rainersigwald** [comment]
Optimistically closing this hoping that the `ImmutableDictionary` change in #5279 fixes it. If you see this on 16.8+, please comment and we can reopen.
