### ISSUE TITLE
MSBuild Pipeline Builds Are Broken

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#5627]
See:
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3956192&view=results
```
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20365.6\tools\Sign.proj(81,5): error MSB4018: The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly.
System.IO.IOException: The process cannot access the file 'C:\A\_work\24\s\artifacts\tmp\Release\ContainerSigning\270\Contents\MSBuild\Current\Bin\zh-Hans\Microsoft.Build.Tasks.Core.resources.dll' because it is being used by another process.

Server stack trace: 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.DotNet.SignTool.RealSignTool.RemovePublicSign(String assemblyPath) in /_/src/Microsoft.DotNet.SignTool/src/RealSignTool.cs:line 73
   at Microsoft.DotNet.SignTool.BatchSignUtil.RemovePublicSign() in /_/src/Microsoft.DotNet.SignTool/src/BatchSignUtil.cs:line 92
   at Microsoft.DotNet.SignTool.BatchSignUtil.Go(Boolean doStrongNameCheck) in /_/src/Microsoft.DotNet.SignTool/src/BatchSignUtil.cs:line 50
   at Microsoft.DotNet.SignTool.SignToolTask.ExecuteImpl() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 227
   at Microsoft.DotNet.SignTool.SignToolTask.Execute() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 142
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3956950&view=results
```
C:\A\_work\15\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20365.6\tools\OptimizationData.targets(110,5): error : No optimization data found for assemblies: C:\A\_work\15\s\artifacts\obj\Microsoft.Build.Framework\Release\net472\Microsoft.Build.Framework.dll [C:\A\_work\15\s\src\Framework\Microsoft.Build.Framework.csproj]
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20365.6\tools\OptimizationData.targets(110,5): error : No optimization data found for assemblies: C:\A\_work\15\s\artifacts\obj\Microsoft.Build.Framework\Release\net472\Microsoft.Build.Framework.dll
```
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3957233&view=results
```
C:\A\_work\5\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20365.6\tools\OptimizationData.targets(110,5): error : No optimization data found for assemblies: C:\A\_work\5\s\artifacts\obj\Microsoft.Build.Framework\Release\net472\Microsoft.Build.Framework.dll [C:\A\_work\5\s\src\Framework\Microsoft.Build.Framework.csproj]
##[error].packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20365.6\tools\OptimizationData.targets(110,5): error : No optimization data found for assemblies: C:\A\_work\5\s\artifacts\obj\Microsoft.Build.Framework\Release\net472\Microsoft.Build.Framework.dll
```

**Comment by BenVillalobos** [comment]
This looks like two separate issues. One where we need to update our OptProf data, and the other is an issue with the agent pool MSBuild uses. We ran into the issue before and had to ping the MicroBuild DL. 

I have an OptProf build running for `master` here: https://dev.azure.com/devdiv/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=771491

I'm going to ping the MicroBuild alias after the OptProf build runs, just in case that fixes our "file in use" issue.

**Comment by BenVillalobos** [comment]
Optprof run built successfully.

Retrying a master build; https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3958119&view=results
and a previously failed `exp/` build https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3956950&view=results

**Comment by Forgind** [comment]
Master build worked last night, so I'm guessing the exp/ build will work now that you have better optprof data. The file in use problem was from one of our PRs that wasn't building or was it still from azdo? If not for CI, is that the microbuild problem?

**Comment by BenVillalobos** [comment]
I believe this is a microbuild problem at this point. I pinged the email thread I used last time to ask for help. Hopefully they get back to me soon. We're now seeing 
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3026: Could not copy "C:\A\_work\15\s\src\Tasks\Microsoft.VisualBasic.targets" to "C:\A\_work\15\s\artifacts\bin\Microsoft.Build.Tasks\Release\net472\Microsoft.VisualBasic.targets". Beginning retry 1 in 1000ms. There is not enough space on the disk. [C:\A\_work\15\s\src\Tasks\Microsoft.Build.Tasks.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3026:   [C:\A\_work\15\s\src\Tasks\Microsoft.Build.Tasks.csproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3026: (NETCORE_ENGINEERING_TELEMETRY=Build) Could not copy "C:\A\_work\15\s\src\Tasks\Microsoft.VisualBasic.targets" to "C:\A\_work\15\s\artifacts\bin\Microsoft.Build.Tasks\Release\net472\Microsoft.VisualBasic.targets". Beginning retry 1 in 1000ms. There is not enough space on the disk.
```

**Comment by Forgind** [comment]
Oh, yeah. That sounds sadly familiar...

**Comment by BenVillalobos** [comment]
The issue is being tracked in the [following IcM](https://portal.microsofticm.com/imp/v3/incidents/details/199905858/home)

**Comment by BenVillalobos** [comment]
### Pipeline builds are no longer automated

I recently pushed exp/test to it's own branch and we merged a few PRs. They should have been picked up via `.vsts-dotnet-ci.yml` but haven't been.
```
trigger:
- master
- exp/*
- vs*
```

Yet no pipeline build is triggered.

**Comment by BenVillalobos** [comment]
I pushed up changes to `exp/test-exp` ([20200817.5](https://dev.azure.com/dnceng/public/_build?definitionId=887)), and it wasn't picked up on our pipelines.

**Comment by MattGal** [comment]
> I pushed up changes to `exp/test-exp` ([20200817.5](https://dev.azure.com/dnceng/public/_build?definitionId=887)), and it wasn't picked up on our pipelines.

This is from the efforts to use the GitHub app to authenticate the dotnet/msbuild repo to dnceng.  Doing so involved breaking the connection between GitHub's dotnet/msbuild repo and dnceng.visualstudio.com.   There are a few options available, let's discuss at your earliest convenience.

**Comment by BenVillalobos** [comment]
Issue was fixed a while back, closing.
