### ISSUE TITLE
Programmatically building a project fails

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/msbuild#5856]
### Issue Description

When using the `BuildManager` API to build a project, almost exactly as shown on https://github.com/dotnet/msbuild/issues/1285#issuecomment-257460878, MSBuild fails.

### Steps to Reproduce

* Download and extract [MSBuildProjectExplorer.zip](https://github.com/dotnet/msbuild/files/5490987/MSBuildProjectExplorer.zip).
* `dotnet restore ConsoleApp1/`
* `cd MSBuildProjectExplorer/`
* `dotnet run`

### Expected Behavior
Building succeeds.

### Actual Behavior
```
__________________________________________________
Project "C:\Users\teots\code\MSBuildProjectExplorer\ConsoleApp1\ConsoleApp1.csproj" (default targets):

You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(63,5): error MSB4018: The "ProcessFrameworkReferences" task failed unexpectedly.
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(63,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.8.0.6860, Culture=n
eutral, PublicKeyToken=31bf3856ad364e35'. Δεν είναι δυνατή η εύρεση του καθορισμένου αρχείου από το σύστημα.
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(63,5): error MSB4018: File name: 'NuGet.Frameworks, Version=5.8.0.6860, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(63,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(63,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(63,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(63,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggi
ngContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
Done building project "ConsoleApp1.csproj" -- FAILED.
```

### Versions & Configurations
The log above is from .NET 5 RC2. Also tested with .NET Core SDK 3.1.403 where it fails, and 2.1.811, where it succeeds.

Tested on Windows and on Linux under WSL (only .NET Core 3.1).

**Comment by BenVillalobos** [comment]
Team Triage: This issue is currently being tracked here: https://github.com/microsoft/MSBuildLocator/issues/86, closing this issue.
