### ISSUE TITLE
Using msbuild with a .net5 single file application

### ISSUE THREAD

**Issue by xtratio** [dotnet/msbuild#6025]
### Issue Description
I am trying to use msbuild api in an application (net5) and publish app as single file.

https://docs.microsoft.com/en-gb/dotnet/core/deploying/single-file

### Steps to Reproduce
- Create a net5 console app vs project
- Add reference to Microsoft.Build nuget package
- Add code `Project project = new Project(NewProjectFileOptions.None);`
- Publish a project with option 'Produce single file'
- Run single file application

Code example: [net5_msbuild_singlefile.zip](https://github.com/dotnet/msbuild/files/5800361/net5_msbuild_singlefile.zip)

The same code works when build as single application with .net 3.1.

### Actual Behavior
System.ArgumentException: The path is empty. (Parameter 'path')
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Utilities.Traits.get_Instance()
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, ToolsetDefinitionLocations toolsetDefinitionLocations)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor()
   at Microsoft.Build.Evaluation.ProjectCollection.get_GlobalProjectCollection()
   at Microsoft.Build.Evaluation.Project..ctor(NewProjectFileOptions newProjectFileOptions)
   at net5_msbuild_singlefile.Program.Main(String[] args)

### Versions & Configurations
.net 5
Microsoft.Build v 16.8.0
windows 10 x64

**Comment by BenVillalobos** [comment]
Team Triage: This is not expected to work. In addition to the managed assemblies, MSBuild needs various files like common.targets and task assemblies that are not direct assembly references. Single file packaging does not include those. Can you instead use [msbuildlocator](https://github.com/microsoft/msbuildlocator) and load MSBuild from the user's instaled SDK directory.

**Comment by BenVillalobos** [comment]
Team Triage: Closing after 1 week due to a solution provided.
