### ISSUE TITLE
Unable to evaluate non SDK style project with Microsoft.Build NuGet package

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/msbuild#6147]
### Issue Description
I have a .Net non SDK style project which I want to evaluate in code using the latest `Microsoft.Build` NuGet package. I am unable to make it work.

### Steps to Reproduce
https://stackoverflow.com/questions/66146972/whats-the-correct-usage-of-microsoft-build-evaluation-fast-forward-to-2021

### Versions & Configurations
```
Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.2.56705
```
I have enterprise edition of VS 2019

**Comment by MarkKharitonov** [comment]
I guess I must provide the issue in full rather than rely on StackOverflow:

So the original question https://stackoverflow.com/questions/24140413/whats-the-correct-usage-of-microsoft-build-evaluation has the following accepted answer:
```
project = new Project(projectPath, new Dictionary<string, string>(), "12.0", new ProjectCollection());
```
This does not work in 2021 with NuGet package Microsoft.Build 16.8.0. 

I would like to evaluate a non SDK style project like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
...
  <Import Project="..\..\..\Tools\MSBuild\Dayforce.targets" />
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
</Project>
```

Please, observe:

**Attempt 1**
```
new Project(projectPath, new Dictionary<string, string>(), "16.0", new ProjectCollection());
```
Results in:
```none
Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "16.0" is unrecognized. Available tools versions are "Current".
```
**Attempt 2**
```
new Project(projectPath, new Dictionary<string, string>(), "Current", new ProjectCollection());
```
Results in:
```none
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\work\CSTool\CSTool\bin\Debug\netcoreapp3.1\Current\Microsoft.Common.props" was not found. Confirm that the expression in the Import declaration "C:\work\CSTool\CSTool\bin\Debug\netcoreapp3.1\Current\Microsoft.Common.props" is correct, and that the file exists on disk.
```
**Attempt 3**
```
new Project(projFilePath, new Dictionary<string, string>
{
    ["MSBuildExtensionsPath"] = @"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild",
}, "Current", new ProjectCollection());
```
Results in:
```none
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\work\CSTool\CSTool\bin\Debug\netcoreapp3.1\Microsoft.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\work\CSTool\CSTool\bin\Debug\netcoreapp3.1\Microsoft.CSharp.targets" is correct, and that the file exists on disk. 
```
We are making progress, Microsoft.Common.props seems to have been imported and now we fail on the last import - Microsoft.CSharp.targets

**Attempt 4**
```
new Project(projFilePath, new Dictionary<string, string>
{
    ["MSBuildExtensionsPath"] = @"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild",
    ["MSBuildBinPath"] = @"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin",
}, "Current", new ProjectCollection());
```
But the result is:
```none
System.ArgumentException: The "MSBuildBinPath" property name is reserved.
```
So, what am I missing?

I managed to do what I wanted. However, none of the `Microsoft.Build` NuGet packages worked as expected by me. I checked all the published versions.

What worked for me is reference the Microsoft.Build Dlls found inside the VS 2019 installation directory. Here is my project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  ...

  <ItemGroup>
    <Reference Include="Microsoft.Build">
      <HintPath>..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Build.Framework">
      <HintPath>..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Framework.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Build.Utilities.Core">
      <HintPath>..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Utilities.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```
And here is the code that works:
```
var project = new Project(projFilePath);
foreach (var compileItem in project.AllEvaluatedItems.Cast<ProjectItem>().Where(item => item.ItemType == "Compile"))
{
    var filePath = compileItem.EvaluatedInclude;
    ...
}
```
I checked the [msbuild github repository][1] - it does not use the NuGet packages either. Instead it includes the source code for all the relevant libraries and just builds them. And these dlls work too just as the VS dlls work.

So, what is the deal with the NuGet packages?


  [1]: https://github.com/dotnet/msbuild

**Comment by MarkKharitonov** [comment]
Anyone?

**Comment by MarkKharitonov** [comment]
@KirillOsenkov - would you be able to comment? Thank you.

**Comment by KirillOsenkov** [comment]
Yes, add the Microsoft.Build.Locator NuGet package and see if it helps

**Comment by KirillOsenkov** [comment]
see https://github.com/microsoft/MSBuildLocator

**Comment by MarkKharitonov** [comment]
I replaced direct assembly references with the latest Microsoft.Build package (16.8) and added Microsoft.Build.Locator 1.4.1. Now the compilation returns this:
```
Build started...
1>------ Build started: Project: CSTool, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Win32.Registry" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>CSTool -> C:\work\CSTool\CSTool\bin\Debug\netcoreapp3.1\CSTool.dll
1>C:\Users\mkharitonov\.nuget\packages\microsoft.build.locator\1.4.1\build\Microsoft.Build.Locator.targets(20,5): error : A PackageReference to Microsoft.Build.* without ExcludeAssets="runtime" exists in your project. This will cause MSBuild assemblies to be copied to your output directory, causing your application to load them at runtime. To use the copy of MSBuild registered by MSBuildLocator, set ExcludeAssets="runtime" on the MSBuild PackageReferences. To disable this check, set the property DisableMSBuildAssemblyCopyCheck=true in your project file (not recommended as you must distributed all of MSBuild + associated toolset). Package(s) referenced: Microsoft.Build
1>Done building project "CSTool.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
The project file is:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ManyConsole" Version="2.0.1" />
    <PackageReference Include="Microsoft.Build" Version="16.8.0" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.4.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.ComponentModel.Composition" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
  </ItemGroup>

</Project>
```
As I understand, the locator wants me to add `ExcludeAssets="runtime"` to Microsoft.Build, ok - added and now compilation returns:
```
Build started...
1>------ Build started: Project: CSTool, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Win32.Registry" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>CSTool -> C:\work\CSTool\CSTool\bin\Debug\netcoreapp3.1\CSTool.dll
1>Done building project "CSTool.csproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
Not ideal, because of the warning, but at least the locator is happy. Running it, however, explodes with:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Source=CSTool
  StackTrace:
   at CSTool.MapAllTypesCmd.Run(String slnListFilePath, String outputFilePath) in C:\work\CSTool\CSTool\MapAllTypesCmd.cs:line 67
   at CSTool.MapAllTypesCmd.Run(String[] remainingArguments) in C:\work\CSTool\CSTool\MapAllTypesCmd.cs:line 27
```
Which kinda makes sense to me, but I did what locator asked me to.

I need more instructions, because it is not obvious at all how this should work.

**Comment by KirillOsenkov** [comment]
At the beginning of your app call MSBuildLocator.RegisterDefault() and make sure it’s in a submethod from Main(). It’s important this runs before any MSBuild assemblies attempt to get loaded.

**Comment by KirillOsenkov** [comment]
See this comment for a sample:
https://github.com/dotnet/msbuild/issues/3434#issuecomment-774280523

We should add a good sample on https://github.com/microsoft/MSBuildLocator

**Comment by MarkKharitonov** [comment]
Still no dice. Followed your instructions and got to the line `var project = new Project(projFilePath);` running which produces
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Build.resources.dll'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```
I need to load **a non SDK** style project.

**Comment by MarkKharitonov** [comment]
Actually the real error which aborts the program is:
```
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files\dotnet\sdk\3.1.101\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.101\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.  c:\dayforce\tip\Services\Platform\WBDataSvc\DataSvc\DataSvc.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile)
   at CSTool.MapAllTypesCmd.Run(String slnListFilePath, String outputFilePath) in C:\work\CSTool\CSTool\MapAllTypesCmd.cs:line 45
   at CSTool.MapAllTypesCmd.Run(String[] remainingArguments) in C:\work\CSTool\CSTool\MapAllTypesCmd.cs:line 27
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at CSTool.Program.Main(String[] args) in C:\work\CSTool\CSTool\Program.cs:line 19
```
As I said - non SDK style project.

**Comment by KirillOsenkov** [comment]
What is the target framework of your project that is using Locator? Make sure to target desktop (net472) and not Core. Also remember to git clean or remove bin/obj every time you change the target framework.

Please post a standalone minimal sample so we can debug it.

**Comment by MarkKharitonov** [comment]
So the tool targets .NET Core, but it analyzes non SDK style projects targeting net472. Changing the tool to target net472 is possible, but I would like to avoid it if possible.

**Comment by KirillOsenkov** [comment]
The tool needs to target net472 (at least for now). The bug above (#3434) is about tools that target .NET Core not supporting this.

**Comment by MarkKharitonov** [comment]
Got it. I prefer to stick to the VS 2019 assemblies for now. Using the NuGet packages is too much fuss at this point.

**Comment by ladipro** [comment]
Team triage: Looks like the issue is understood and mitigated. Please reopen otherwise.
