### ISSUE TITLE
Flaky test: Microsoft.Build.UnitTests.BackEnd.TaskBuilder_Tests.TasksCanAddRecursiveDirBuiltInMetadata

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6267]
`TasksCanAddRecursiveDirBuiltInMetadata` failed for me but passed under debugger:
https://github.com/dotnet/msbuild/blob/13522d2466ae1634177e2a6a40fefaedff95139c/src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs#L355

**Comment by KirillOsenkov** [comment]
Microsoft.Build.UnitTests.BackEnd.TaskBuilder_Tests.TasksCanAddRecursiveDirBuiltInMetadata
Log was not expected to contain '[]', but did.\r\nExpected: True\r\nActual:   False
   at Microsoft.Build.UnitTests.MockLogger.AssertLogDoesntContain(String contains) in C:\msbuild\src\Shared\UnitTests\MockLogger.cs:line 482
   at Microsoft.Build.UnitTests.BackEnd.TaskBuilder_Tests.TasksCanAddRecursiveDirBuiltInMetadata() in C:\msbuild\src\Build.UnitTests\BackEnd\TaskBuilder_Tests.cs:line 355

**Comment by KirillOsenkov** [comment]
`C:\msbuild\artifacts\TestResults\Debug\Microsoft.Build.Engine.UnitTests_net5.0_x64.html`

**Comment by KirillOsenkov** [comment]
It is intermittent.
