### ISSUE TITLE
OOM in MSBUILD x64 Windows build when /v:diag or  /v:detailed

### ISSUE THREAD

**Issue by zhouwei25** [dotnet/msbuild#6276]
When I change `msbuild /v:normal` to `msbuild /v:diagnostic` or `msbuild /v:detailed` , this error will occur, why?

> 2016-12-16T12:11:06.4902191Z                    Set Property: SdkInstallerNupkgFile=D:\DOTNET-CLI-W004\_work\4\s\/artifacts/win10-x86/packages/VS.Redist.Common.Net.Core.SDK.x86.1.0.0-preview5-004262.nupkg
2016-12-16T12:13:15.3666181Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2016-12-16T12:13:15.3666181Z System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
2016-12-16T12:13:15.3666181Z    at Microsoft.Build.Execution.BuildManager.EndBuild()
2016-12-16T12:13:15.3666181Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
2016-12-16T12:13:15.3666181Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2016-12-16T12:13:15.3666181Z System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
2016-12-16T12:13:15.3666181Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
2016-12-16T12:13:15.3666181Z    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
2016-12-16T12:13:15.3666181Z Unhandled Exception: OutOfMemoryException.

![image](https://user-images.githubusercontent.com/52485244/111608858-a42bf600-8814-11eb-925d-98fa1be4f82a.png)

It's the same as https://github.com/dotnet/msbuild/issues/1491

**Comment by BenVillalobos** [comment]
Team Triage: @rokonec Could you take a look at this? It's related to something you discussed with @rainersigwald recently.

**Comment by rokonec** [comment]
@zhouwei25 is there a way we can reproduce it? 
Does it fail with `msbuild /bl` binary log as well?
What os the version of msbuild?
Do you experience same issue with `Visual Studio 2019 version 16.10`?

**Comment by rokonec** [comment]
Closing for inactivity. 
Please feel free to reopen if needed.
