### ISSUE TITLE
Node Crash When Logging TaskParameters

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#6379]
Original Feedback Ticket: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1314638 (the "Move to Github") button failed)

### Issue Description
Caused by https://github.com/dotnet/msbuild/pull/6155 /cc: @KirillOsenkov 

### Stack Trace
```
System.AppDomainUnloadedException: The application domain in which the thread was running has been unloaded.

Server stack trace:

at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)

at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)

at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)

Exception rethrown at [0]:

at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)

at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)

at Microsoft.Build.Framework.IMetadataContainer.EnumerateMetadata()

at Microsoft.Build.Framework.ITaskItemExtensions.EnumerateMetadata(ITaskItem taskItem)

at Microsoft.Build.Framework.TaskParameterEventArgs.WriteMetadata(BinaryWriter writer, ITaskItem taskItem)

at Microsoft.Build.Framework.TaskParameterEventArgs.WriteItem(BinaryWriter writer, Object item)

at Microsoft.Build.Framework.TaskParameterEventArgs.WriteItems(BinaryWriter writer, IList items)

at Microsoft.Build.Framework.TaskParameterEventArgs.WriteToStream(BinaryWriter writer)

at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)

at Microsoft.Build.Shared.LogMessagePacketBase.Translate(ITranslator translator)

at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
```

### Versions & Configurations
Build Number: 16.10.31213.239
Product Version: 16.10.0-preview-2.0

**Comment by KirillOsenkov** [comment]
ouch. Taking a look.

**Comment by KirillOsenkov** [comment]
For validation I've also tried running this logic always (regardless of appdomains) and it worked fine.
