### ISSUE TITLE
NullReferenceException in SpanBasedConcatenator when evaluating target dependencies

### ISSUE THREAD

**Issue by dfederm** [dotnet/msbuild#6413]
Seeing this exception when building a project:

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Evaluation.Expander`2.SpanBasedConcatenator.Add(Object obj)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.BackEnd.TargetEntry.GetDependencies(ProjectLoggingContext projectLoggingContext)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__58.MoveNext()
```

It does *not* repro with `16.9.0+5e4b48a27` but does with `16.10.0-preview-21181-05+80f316e90` and `16.10.0-preview-21227-06+1d1fec7c4`.

I'll try to get a minimal repro, but this is happening in a private repo I'm not very familiar with. Ping me on Teams for instructions cloning the repo this is happening to in the meantime.

**Comment by dfederm** [comment]
Found a minimal repro:

```xml
<Project>
  <Target Name="Build" Condition="'$([System.Environment]::GetEnvironmentVariable(`Bar`))' == 'Baz'" />
</Project>
```

**Comment by dfederm** [comment]
My best guess is that `null` should be treated as `string.Empty` in this case.
