### ISSUE TITLE
MS 

### ISSUE THREAD

**Issue by jdmerinor** [dotnet/msbuild#6654]
### Issue Description
Real exception (Could not load file or assembly 'System.Collections.Immutable) is hidden behind (Microsoft.Build.Exceptions.InvalidProjectFileException: 'The SDK 'Microsoft.NET.Sdk' specified could not be found. PathToProject).
I already fixed the underlying issue but I think this should not be hidden like this, it should probably be set as an inner exception or something like that.

### Full detail of exceptions being thrown
-> **FIRST exception that happens**
System.Runtime.InteropServices.COMException: 'Element not found. (Exception from HRESULT: 0x80070490)' in:
![Stacktrace first Exception](https://user-images.githubusercontent.com/14632949/124531562-18d18180-de52-11eb-89fd-dd430fd6bdd5.png)
-> **SECOND exception that happens and that I would expect to be reported**
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
Stacktrace:
   ```
at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion)
   at Microsoft.DotNet.MSBuildSdkResolver.DotNetMSBuildSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext context, SdkResultFactory factory)
```
![Second  exception full stacktrace](https://user-images.githubusercontent.com/14632949/124532499-0a846500-de54-11eb-8ac5-75b33a53ffe1.png)
-> **Actual exception that I get without inner exceptions:**
"Microsoft.Build.Exceptions.InvalidProjectFileException: 'The SDK 'Microsoft.NET.Sdk' specified could not be found. PathToProject"
Stacktrace:
   `at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)`
![Third and actual stacktrace that I get](https://user-images.githubusercontent.com/14632949/124532773-7ebf0880-de54-11eb-9d18-2afb71d5a6b3.png)

### Steps to Reproduce
The issue happens when trying to create 
``` cs
new Project(fullPath, globalProperties, null, projectCollection);
```

### Expected Behavior
I would expect it to fail with "System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Collections.Immutable, Version=5.0.0.0" or at least have that as the inner exception of the error that I'm getting (Microsoft.Build.Exceptions.InvalidProjectFileException: 'The SDK 'Microsoft.NET.Sdk' specified could not be found. PathToProject")

### Actual Behavior
The actual error is "Microsoft.Build.Exceptions.InvalidProjectFileException: 'The SDK 'Microsoft.NET.Sdk' specified could not be found. PathToProject" and does not contain any indication of that the actual error is

### Versions & Configurations
MSBuild version 16.10.1.27004

**Comment by BenVillalobos** [comment]
Team Triage: Are you using [MSBuildLocator](https://github.com/microsoft/MSBuildLocator)?

**Comment by jdmerinor** [comment]
I'm using MSBuildLocator indeed, and upgrading it to the latest version solved my issue, but it was quite tricky to determine what was going south because of the exception being swollen so I was able to get to it by unticking the Debug Just My Code in VS. So that's why I think maybe the exception reporting is wrong and needs better reporting?
