### ISSUE TITLE
Build fails with `*.runtimeconfig.json ` being used by another process when framework explicitly specified with `--framework:net5.0` in dotnet build 

### ISSUE THREAD

**Issue by wingrime** [dotnet/msbuild#6690]
### Issue Description
 Project build fails when `--framework:net5.0` added to commandline 

```
/usr/share/dotnet/sdk/5.0.302/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(248,5): error MSB4018: The "GenerateRuntimeConfigurationFiles" task failed unexpectedly.
System.IO.IOException: The process cannot access the file '/build/SkbKontur.BusinessTrip.TransferDb/bin/Release/net5.0/SkbKontur.BusinessTrip.TransferDb.runtimeconfig.json' because it is being used by another process.
   at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteToJsonFile(String fileName, Object value)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteRuntimeConfig(RuntimeFramework[] runtimeFrameworks, LockFileTargetLibrary platformLibrary, Boolean isFrameworkDependent, IList`1 packageFolders)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/build/SkbKontur.BusinessTrip.TransferDb/SkbKontur.BusinessTrip.TransferDb.csproj]
```

### Steps to Reproduce
Build project in offical docker container (sdk  5.0.302) with framework constraint:

```
dotnet build  -c Release --framework:net5.0
```
but, without framework constraint all seems ok:

```
dotnet build  -c Release  
```

### Expected Behavior

Project builds

### Actual Behavior
Binlogs with successed and failed builds are in attachments:
[Binlogs.zip](https://github.com/dotnet/msbuild/files/6848208/Binlogs.zip)

**Comment by BenVillalobos** [comment]
Does this also happen when building with `--graph`? It could be a race condition with SkbKontur.BusinessTrip.TransferDb.csproj and SkbKontur.BusinessTrip.TransferDb.Tests.csproj building it through a ProjectReference.

**Comment by wingrime** [comment]
[graph-error-log.zip](https://github.com/dotnet/msbuild/files/6883297/graph-error-log.zip)
Same error with --graph on linux

**Comment by rainersigwald** [comment]
I think this is an instance of https://github.com/dotnet/sdk/issues/9585. Avoid specifying `--framework` when building a solution.
