### ISSUE TITLE
Can't write MSBuild_Logs to C:\windows\system32

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6721]
If MSBuild.exe is run with the current directory pointing to C:\windows\system32 you may occasionally see the following failure.txt file next to the project being built:

```
UNHANDLED EXCEPTIONS FROM PROCESS 9724:
=====================
7/30/2021 8:32:57 PM
System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\MSBuild_Logs' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Build.Shared.ExceptionHandling.DumpExceptionToFile(Exception ex)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===================
```

I think it shouldn't attempt to write to MSBuild_Logs in this case and try the location next to the project instead.

**Comment by KirillOsenkov** [comment]
Turns out I have the amazing LocalDumps registry key enabled, and it got me a nice dump for this. The exception MSBuild tried to write to the text file in C:\windows\system32 was:

```
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode) in f:\dd\ndp\fx\src\Core\System\IO\Pipes\PipeStream.cs:line 1168
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state) in f:\dd\ndp\fx\src\Core\System\IO\Pipes\PipeStream.cs:line 560
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count) in f:\dd\ndp\fx\src\Core\System\IO\Pipes\PipeStream.cs:line 454
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count) in f:\dd\ndp\fx\src\Core\System\IO\Pipes\PipeStream.cs:line 440
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump) in /_/src/Shared/NodeEndpointOutOfProcBase.cs:line 618
```

**Comment by KirillOsenkov** [comment]
And this is the location that tried to write to file:
https://github.com/dotnet/msbuild/blob/b6e7d6051a3c3f595bfa11bd3b2749c0c8cc7f3c/src/Shared/NodeEndpointOutOfProcBase.cs#L625

**Comment by KirillOsenkov** [comment]
I suspect it was caused by two unrelated builds stealing nodes from each other, or some other crossfire of inter-node communication between unrelated builds.

**Comment by KirillOsenkov** [comment]
I suppose I could repro on demand if someone was super interested. Basically trigger a build in the IDE and at the same time trigger a build at command line of the same large-ish solution and make sure the build is not incremental (otherwise nothing much will happen).

**Comment by KirillOsenkov** [comment]
Certainly a low-pri bug I think.

**Comment by Forgind** [comment]
I'm not sure about `try the location next to the project instead` because users might not want files in unexpected locations. Depending on their git settings, it might even show up as something to commit. On the other hand, it's nice to have the logs somewhere, and you can more easily move them around after your build than resetting everything and running the build again, but that assumes that you know where the log is. It might be reasonable to send a message or warning if this sort of thing happens (if that isn't already true), and if we end up making the log somewhere, we should maybe mention where in the message/warning.

**Comment by Forgind** [comment]
https://github.com/dotnet/msbuild/pull/7366 likely made this scenario better. It looks like the fallback schema is MSBUILDDEBUGPATH --> current directory --> temp, and that third, at least, should (almost) always be writable.

It's potentially important that KirillOsenkov hit this from DumpExceptionToFile, however. We should check if that uses the same fallback logic. (Potentially unify if not?)

**Comment by vlada-shubina** [comment]
I also verified, that `ExceptionHandling.DumpExceptionToFile` uses same logic and will be using path in the temp in this case.

@Forgind @rainersigwald, suggesting to close as already fixed with https://github.com/dotnet/msbuild/pull/7366.

**Comment by vlada-shubina** [comment]
Just a note to verify, if having logs from different runs in same folder is as expected:
```
    Directory: %TEMP%\MSBuildTempvshubina\MSBuild_Logs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/19/2023  1:38 PM         351423 CentralNode_MSBuild_PID=18860_x86_BuildManager_Default.binlog
-a---           1/19/2023  1:28 PM         351411 CentralNode_MSBuild_PID=2936_x86_BuildManager_Default.binlog
-a---           1/19/2023  1:39 PM         352278 CentralNode_MSBuild_PID=30624_x86_BuildManager_Default.binlog
-a---           1/19/2023  1:38 PM            605 EngineTrace_18860.txt
-a---           1/19/2023  1:28 PM            604 EngineTrace_2936.txt
-a---           1/19/2023  1:39 PM            604 EngineTrace_30624.txt
-a---           1/19/2023  1:38 PM           1083 SchedulerState_18860.txt
-a---           1/19/2023  1:28 PM           1083 SchedulerState_2936.txt
-a---           1/19/2023  1:39 PM           1083 SchedulerState_30624.txt
-a---           1/19/2023  1:38 PM            689 SchedulerTrace_18860.txt
-a---           1/19/2023  1:28 PM            689 SchedulerTrace_2936.txt
-a---           1/19/2023  1:39 PM            689 SchedulerTrace_30624.txt

```

**Comment by Forgind** [comment]
> Just a note to verify, if having logs from different runs in same folder is as expected:
> 
> ```
>     Directory: %TEMP%\MSBuildTempvshubina\MSBuild_Logs
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a---           1/19/2023  1:38 PM         351423 CentralNode_MSBuild_PID=18860_x86_BuildManager_Default.binlog
> -a---           1/19/2023  1:28 PM         351411 CentralNode_MSBuild_PID=2936_x86_BuildManager_Default.binlog
> -a---           1/19/2023  1:39 PM         352278 CentralNode_MSBuild_PID=30624_x86_BuildManager_Default.binlog
> -a---           1/19/2023  1:38 PM            605 EngineTrace_18860.txt
> -a---           1/19/2023  1:28 PM            604 EngineTrace_2936.txt
> -a---           1/19/2023  1:39 PM            604 EngineTrace_30624.txt
> -a---           1/19/2023  1:38 PM           1083 SchedulerState_18860.txt
> -a---           1/19/2023  1:28 PM           1083 SchedulerState_2936.txt
> -a---           1/19/2023  1:39 PM           1083 SchedulerState_30624.txt
> -a---           1/19/2023  1:38 PM            689 SchedulerTrace_18860.txt
> -a---           1/19/2023  1:28 PM            689 SchedulerTrace_2936.txt
> -a---           1/19/2023  1:39 PM            689 SchedulerTrace_30624.txt
> ```

I don't think that's ideal, but that's what I would've expected. You can always sort by when they were made, so I don't think it's a big deal. If you want to change that, I wouldn't be opposed, but I'd consider it pretty low priority.

Closing as fixed.
