### ISSUE TITLE
Custom Task, MSBuild Fails to find System.Runtime

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#6796]
### Issue Description
Creating boilerplate A.proj (task project) and B.proj (calls the task) fails with MSB4018 can't find System.Runtime. 

### Project A (Task Project)
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
  </PropertyGroup>

  <ItemGroup>
        <PackageReference Include="Microsoft.Build.Utilities.Core" Version="16.10.0" />
  </ItemGroup>
</Project>

```

### Project B (Calls the task in the proj file)
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

    <UsingTask TaskName="foo" AssemblyFile="..\task\bin\Debug\net5.0\task.dll" />

    <Target Name="Build2" AfterTargets="Build">
        <foo CreateArchiveName="%(Archive)" 
          BaseArchives="@(ArchiveBase->'%(Identity)')"
          Installer="@(Installer->'%(Identity)')" />
    </Target>

</Project>
```

### Task Code
```c#
using Microsoft.Build.Utilities;
using Microsoft.Build.Framework;
using System;
using System.Diagnostics;

namespace Foobar
{
    public class foo : Task
    {
        public string CreateArchiveName { get; set; }

        public ITaskItem[] BaseArchives { get; set; }

        public ITaskItem[] Installer { get; set; }

        public override bool Execute()
        {
            // var processInfo = new ProcessStartInfo();
            // processInfo.FileName = "cmd";
            // processInfo.RedirectStandardInput = true;
            // processInfo.UseShellExecute = false;
            // processInfo.WorkingDirectory = Location;

            // var a = Process.Start(processInfo);

            // a.StandardInput.WriteLine("exit");
            Console.WriteLine("CreateArchiveName: " + CreateArchiveName);

            return true;
        }
    }
}
```

### Steps to Reproduce
`dotnet new console -o proj`
`dotnet new console -o task`
Copy project & .cs files from above into the relevant projects.
restore & build both projects.
call `msbuild proj\proj.csproj`

### Expected Behavior
Build succeeded

### Actual Behavior
```
"C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj" (default target) (1) ->
(Build2 target) ->
  C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: The "foo" task failed unexpectedly.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, Publ 
icKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018:    at Foobar.foo.Execute()
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018:
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2019\Dogfood\MSBuild\Current\Bin\MSBuild.exe    
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: --- A detailed error log follows.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018:
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: === Pre-bind state information ===
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: DisplayName = System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018:  (Fully-specified)
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Dogfood/MSBuild/Current/Bin/
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Initial PrivatePath = NULL
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: Calling assembly : task, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: ===
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: This bind starts in LoadFrom load context.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like 
 with Assembly.Load().
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Dogfood\MSBuild\Current\B 
in\MSBuild.exe.Config
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Using host configuration file:
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Post-policy reference: System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Dogfood/MSBuild/Current/ 
Bin/System.Runtime.DLL.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Dogfood/MSBuild/Current/ 
Bin/System.Runtime/System.Runtime.DLL.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Dogfood/MSBuild/Current/ 
Bin/System.Runtime.EXE.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Dogfood/MSBuild/Current/ 
Bin/System.Runtime/System.Runtime.EXE.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Attempting download of new URL file:///C:/src/temp/8-30/evaluation/NEW/task/bin/Debug/net5.0/System.Runtime.DLL.    
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Attempting download of new URL file:///C:/src/temp/8-30/evaluation/NEW/task/bin/Debug/net5.0/System.Runtime/System. 
Runtime.DLL.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Attempting download of new URL file:///C:/src/temp/8-30/evaluation/NEW/task/bin/Debug/net5.0/System.Runtime.EXE.    
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018: LOG: Attempting download of new URL file:///C:/src/temp/8-30/evaluation/NEW/task/bin/Debug/net5.0/System.Runtime/System. 
Runtime.EXE.
C:\src\temp\8-30\evaluation\NEW\proj\proj.csproj(11,7): error MSB4018:
```

### Analysis
`dotnet build` works just fine.

### Versions & Configurations
dotnet 5.0.400

msbuild `16.11.0+0538acc04`

**Comment by BenVillalobos** [comment]
Turns out you can't load a net5 dll on .net framework! Closing

**Comment by jzabroski** [comment]
Yes, *smacks forehead*.

...And, you can use MSBuildRuntimeType to guard against running a .NET 8 dll on MSBuild for .NET Framework.  
...And, in .NET 8, there are breaking changes in version requirements for MSBuild custom tasks: https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/version-requirements

> * 8.0.100 requires version 17.7 to be loaded but only supports targeting .NET 7 in that version.
> * 8.0.200 requires version 17.8.
> * **8.0.400 requires version 17.9.**

**Comment by baronfel** [comment]
In general MSBuild dependency versions track SDK releases - you can use https://aka.ms/dotnet/matrixofpaine to see how those versions map to each other. 

For task authors, we recommend that you target as low an MSBuild dependency as possible to ensure maximum compatibility with the SDK hosting environment.
