### ISSUE TITLE
WorkloadManifestCompositionException stack dumped from SdkResolverService

### ISSUE THREAD

**Issue by danmoseley** [dotnet/msbuild#6964]
From a customer using Version 17.0.0 Preview 5.0 [31807.328.d17.0], their machine got into some bad state, and they get this output.

Assuming this is not indicating a bug in MSBuild, but rather a bad machine state, the exception should be caught so that only the error message is shown.
```
C:\temp\ConsoleApp1\ConsoleApp1>dotnet run
C:\temp\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj : error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.0-rc.2.21474.1' is lower than version '6.0.0-rc.1.21430.3' required by manifest 'microsoft.net.workload.mono.toolchain' [C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.workload.mono.toolchain\WorkloadManifest.json]
C:\temp\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
C:\temp\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
C:\temp\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir)
C:\temp\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
C:\temp\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj : error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)""
```

**Comment by danmoseley** [comment]
The bug then is that the exception message contains the stack. I agree it's low priority.
