### ISSUE TITLE
msbuild project.target gave an internal error

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#7172]
### Steps to Reproduce

I made project A that referenced project B and added both to a solution. B has a target T. I built the solution with /t:B.T.

### Expected Behavior

I wasn't sure what to expect: throwing an error or building T as desired.

### Actual Behavior

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.ArgumentException: The name "classlib.PrintInitial" contains an invalid character ".".
   at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectTargetElement.set_Name(String value)
   at Microsoft.Build.Construction.ProjectTargetElement.CreateDisconnected(String name, ProjectRootElement containingProject)
   at Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified, List`1 projectsInOrder)
   at Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified)
   at Microsoft.Build.Construction.SolutionProjectGenerator.Generate()
   at Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, BuildEventContext projectBuildEventContext, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass98_0.<IssueBuildRequestForBuildSubmission>g__IssueBuildSubmissionToSchedulerImpl|1(BuildSubmission submission, Boolean allowMainThreadBuild)
```

### Analysis

Haven't looked into it yet.

### Versions & Configurations

17.0.0.52104

**Comment by rainersigwald** [comment]
That syntax is not valid so this should instead throw a nicer user-facing error.
