### ISSUE TITLE
MissingRestorePropertyError doesn't exist

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#7218]
### Issue Description

Pretty minor issue, but MissingRestorePropertyError isn't a thing, so we shouldn't pretend we can throw it. We should make it a thing.

### Steps to Reproduce

`dotnet build /rp:` on anything.

### Expected Behavior

Some nice error message about how /rp is missing a parameter.

### Actual Behavior

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Missing resource 'MissingRestorePropertyError'
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Shared.AssemblyResources.GetString(String name)
   at Microsoft.Build.Shared.ResourceUtilities.FormatResourceStringStripCodeAndKeyword(String& code, String& helpKeyword, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ResourceUtilities.FormatResourceStringStripCodeAndKeyword(String resourceName, Object[] args)
   at Microsoft.Build.CommandLine.CommandLineSwitchException.Throw(String messageResourceName, String commandLineArg, String[] messageArgs)
   at Microsoft.Build.CommandLine.CommandLineSwitchException.Throw(String messageResourceName, String commandLineArg)
   at Microsoft.Build.CommandLine.CommandLineSwitches.ThrowErrors()
   at Microsoft.Build.CommandLine.MSBuildApp.ProcessCommandLineSwitches(CommandLineSwitches switchesFromAutoResponseFile, CommandLineSwitches switchesNotFromAutoResponseFile, String& projectFile, String[]& targets, String& toolsVersion, Dictionary`2& globalProperties, ILogger[]& loggers, LoggerVerbosity& verbosity, List`1& distributedLoggerRecords, Int32& cpuCount, Boolean& enableNodeReuse, TextWriter& preprocessWriter, TextWriter& targetsWriter, Boolean& detailedSummary, ISet`1& warningsAsErrors, ISet`1& warningsAsMessages, Boolean& enableRestore, Boolean& interactive, ProfilerLogger& profilerLogger, Boolean& enableProfiler, Dictionary`2& restoreProperties, Boolean& isolateProjects, GraphBuildOptions& graphBuild, String[]& inputResultsCaches, String& outputResultsCache, Boolean& lowPriority, Boolean recursing)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
Unhandled exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Missing resource 'MissingRestorePropertyError'
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Shared.AssemblyResources.GetString(String name)
   at Microsoft.Build.Shared.ResourceUtilities.FormatResourceStringStripCodeAndKeyword(String& code, String& helpKeyword, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ResourceUtilities.FormatResourceStringStripCodeAndKeyword(String resourceName, Object[] args)
   at Microsoft.Build.CommandLine.CommandLineSwitchException.Throw(String messageResourceName, String commandLineArg, String[] messageArgs)
   at Microsoft.Build.CommandLine.CommandLineSwitchException.Throw(String messageResourceName, String commandLineArg)
   at Microsoft.Build.CommandLine.CommandLineSwitches.ThrowErrors()
   at Microsoft.Build.CommandLine.MSBuildApp.ProcessCommandLineSwitches(CommandLineSwitches switchesFromAutoResponseFile, CommandLineSwitches switchesNotFromAutoResponseFile, String& projectFile, String[]& targets, String& toolsVersion, Dictionary`2& globalProperties, ILogger[]& loggers, LoggerVerbosity& verbosity, List`1& distributedLoggerRecords, Int32& cpuCount, Boolean& enableNodeReuse, TextWriter& preprocessWriter, TextWriter& targetsWriter, Boolean& detailedSummary, ISet`1& warningsAsErrors, ISet`1& warningsAsMessages, Boolean& enableRestore, Boolean& interactive, ProfilerLogger& profilerLogger, Boolean& enableProfiler, Dictionary`2& restoreProperties, Boolean& isolateProjects, GraphBuildOptions& graphBuild, String[]& inputResultsCaches, String& outputResultsCache, Boolean& lowPriority, Boolean recursing)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
   at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.ExecuteInProc(String[] arguments)
```

### Analysis

We probably just need to add text for the MissingRestorePropertyError, and everything will be good.

**Comment by jrdodds** [comment]
> We probably just need to remove the line that pretends /rp is a thing

 If /rp is not a 'thing' then the documentation and the command line help also needs correcting. The /rp switch works with the /r switch.

![image](https://user-images.githubusercontent.com/1728516/148707154-c46f6203-e68b-499f-a374-b75645e86687.png)

Content: [MSBuild Command-Line Reference - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022)
Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-command-line-reference.md)

string resource for command line help:
https://github.com/dotnet/msbuild/blob/deace0b2a539737c1c80265da741758093884212/src/MSBuild/Resources/Strings.resx#L693-L709

It looks like 'MissingRestorePropertyError' wasn't part of
https://github.com/dotnet/msbuild/commit/5213af78d17613417e5b715e7f83100dc1574ad6#diff-6a9b25cb1bbedfff77ff16e9ecb10adc8dd2b22872a00a6bb1b3454432f3fd92
and wasn't added later.

**Comment by Forgind** [comment]
@jrdodds, to be honest, I hadn't properly tested this, so thanks for commenting. Edited my comment.

**Comment by jrdodds** [comment]
@Forgind would there be a MSB#### error code defined for this error message somewhere?

**Comment by jrdodds** [comment]
@Forgind On further investigation, the /p and /rp switches share the 'InvalidPropertyError'. I suspect the intent was to also share the 'MissingPropertyError'. I made a change accordingly.

(Hopefully I performed the branching and pull request correctly. Some of this is new to me.)

Thanks

**Comment by Forgind** [comment]
> @Forgind On further investigation, the /p and /rp switches share the 'InvalidPropertyError'. I suspect the intent was to also share the 'MissingPropertyError'. I made a change accordingly.
> 
> (Hopefully I performed the branching and pull request correctly. Some of this is new to me.)
> 
> Thanks

Branching and PR look good!

I'm wondering if it would be confusing to see "missing property" when these properties don't apply to most of the build. I'll bring it up in our PR review meeting on Monday and see what people think.

**Comment by jrdodds** [comment]
A 'missing property' is using /p or /rp with no values. The error message will include the switch that generated the error, either /p or /rp, so the message is not without some context.

**Comment by jrdodds** [comment]
The Invalid Property error, which was already extant, reports the property without the switch. This could be considered a separate issue.

### Example
```
msbuild test.proj /p:foo /rp:foo
``` 
generates
```
MSBUILD : error MSB1006: Property is not valid.
Switch: foo
```
This is a simplistic example, but the error doesn't indicate which switch is at issue.

**Comment by Forgind** [comment]
I think that's true of other switches when you skip the argument, though. As an example:
```
> dotnet build /nodemode
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1033: Node number is not valid. .
Switch: 0

For switch syntax, type "MSBuild -help"
```

(Which to me suggests another bug report.) Pertinently, it didn't say which switch; you were supposed to infer it from the message.

**Comment by Forgind** [comment]
@baronfel, do you have an opinion on whether /rp: and /p: can share an error message, or they should each get their own? Also, 
> reports the property without the switch

It seems that some switches errors report the switch and others don't. Maybe move to one or the other to help clarify?

/CC: @BenVillalobos

**Comment by baronfel** [comment]
I think in this case the two can share a message. They're both the same _kind_ of argument - specifying a property - the main difference is when the property comes into play. I do agree that the error message for an invalid switch value should also report the switch that was invalid.
