### ISSUE TITLE
Unit Tests Fail for ProcessorArchitecture.ARM64 on Apple Silicon

### ISSUE THREAD

**Issue by jrdodds** [dotnet/msbuild#7292]
### Issue Description

Tested on macOS Monterey v12.1 with Apple M1 Pro and .Net SDK Arm64. 

Running unit tests fails because test methods [ValidateConvertDotNetFrameworkArchitectureToProcessorArchitecture](https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs#L47) and [ValidateCurrentProcessorArchitectureCall](https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs#L41) fail when the value of `ProcessorArchitecture.CurrentProcessArchitecture` is `ProcessorArchitecture.ARM64`.

### Steps to Reproduce

Follow the instructions for building on [macOS](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md#unix). Use a machine with an Apple Silicon chip. Run the command `./build.sh --test` as in the instructions.

### Expected Behavior

Tests are expected to complete with no errors.

### Actual Behavior

The test run fails:
```
XUnit : error : Tests failed: [...]/msbuild/artifacts/TestResults/Debug/Microsoft.Build.Utilities.UnitTests_net6.0_x64.html [net6.0|x64] [[...]/msbuild/src/Utilities.UnitTests/Microsoft.Build.Utilities.UnitTests.csproj]
    0 Warning(s)
    1 Error(s)
```

The log shows 2 failures for the Microsoft.Build.Utilities.UnitTests.csproj project:
```
BuildUtilities.ProcessorArchitecture.CurrentProcessArchitecture is: ARM64
  Microsoft.Build.UnitTests.ProcessorArchitectureTests.ValidateConvertDotNetFrameworkArchitectureToProcessorArchitecture [FAIL]
    System.InvalidOperationException : Untested or new ProcessorArchitecture type
      Stack Trace:
      [...]/msbuild/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs(93,0): at Microsoft.Build.UnitTests.ProcessorArchitectureTests.ValidateConvertDotNetFrameworkArchitectureToProcessorArchitecture()
  Microsoft.Build.UnitTests.ProcessorArchitectureTests.ValidateCurrentProcessorArchitectureCall [FAIL]
    Shouldly.ShouldAssertException : "ARM64"
        should be
    null
        but was not
        difference
    Difference     |  |    |    |    |    |   
                   | \|/  \|/  \|/  \|/  \|/  
    Index          | 0    1    2    3    4    
    Expected Value | n    u    l    l         
    Actual Value   | A    R    M    6    4    
    Expected Code  | 110  117  108  108       
    Actual Code    | 65   82   77   54   52   
      Stack Trace:
         at Shouldly.ShouldBeStringTestExtensions.ExecuteAssertion(IAssertion assertion, Func`1 customMessage)
         at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected, Func`1 customMessage, StringCompareShould options)
         at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected, StringCompareShould options)
         at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected)
      [...]/msbuild/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs(43,0): at Microsoft.Build.UnitTests.ProcessorArchitectureTests.ValidateCurrentProcessorArchitectureCall()
```

(I have removed part of the paths for privacy.)

### Analysis

The ARM64 const (defined in ProcessorArchitecture.cs) is not handled by the [ProcessorArchitectureTests](https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Utilities.UnitTests/ProcessorArchitecture_Tests.cs) unit test class.

https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Utilities/ProcessorArchitecture.cs#L43-L48

### Versions & Configurations

```
% dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

```
% dotnet msbuild -version
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

17.0.0.52104
```

**Comment by jrdodds** [comment]
Retested using the 'arm64-processorarch-ut' branch and the unit tests now succeed.

```
  Tests succeeded: /Users/jrdodds/Projects/dotnet/msbuild/artifacts/bin/Microsoft.Build.Utilities.UnitTests/Debug/net6.0/Microsoft.Build.Utilities.UnitTests.dll [net6.0|x64]
```

**Comment by xsoheilalizadeh** [comment]
I'm running  [dotnet/aspnetcore](https://github.com/dotent/aspnetcore) tests on macOS ARM64 and I get `[net7.0|x64]` at the end of the result. I'm curious to know why it's x64 while I'm running on a x64 machine.

```
dotnet/aspnetcore [main●] » ./eng/build.sh --arch arm64 --os-name osx --test --projects ../src/Features/JsonPatch/test/Microsoft.AspNetCore.JsonPatch.Tests.csproj

dotnet-install: .NET Core Runtime with version '7.0.0-preview.3.22163.2' is already installed.
  Determining projects to restore...
  Determining projects to restore...
  All projects are up-to-date for restore.
  All projects are up-to-date for restore.
  Microsoft.AspNetCore.JsonPatch -> /Users/soheilalizadeh/Codes/dotnet/aspnetcore/artifacts/bin/Microsoft.AspNetCore.JsonPatch/Debug/net462/Microsoft.AspNetCore.JsonPatch.dll
  Microsoft.AspNetCore.Testing -> /Users/soheilalizadeh/Codes/dotnet/aspnetcore/artifacts/bin/Microsoft.AspNetCore.Testing/Debug/net462/Microsoft.AspNetCore.Testing.dll
  Microsoft.AspNetCore.Testing -> /Users/soheilalizadeh/Codes/dotnet/aspnetcore/artifacts/bin/Microsoft.AspNetCore.Testing/Debug/net7.0/Microsoft.AspNetCore.Testing.dll
  Microsoft.AspNetCore.JsonPatch -> /Users/soheilalizadeh/Codes/dotnet/aspnetcore/artifacts/bin/Microsoft.AspNetCore.JsonPatch/Debug/net7.0/Microsoft.AspNetCore.JsonPatch.dll
  Microsoft.AspNetCore.JsonPatch.Tests -> /Users/soheilalizadeh/Codes/dotnet/aspnetcore/artifacts/bin/Microsoft.AspNetCore.JsonPatch.Tests/Debug/net462/Microsoft.AspNetCore.JsonPatch.Tests.dll
  Microsoft.AspNetCore.JsonPatch.Tests -> /Users/soheilalizadeh/Codes/dotnet/aspnetcore/artifacts/bin/Microsoft.AspNetCore.JsonPatch.Tests/Debug/net7.0/Microsoft.AspNetCore.JsonPatch.Tests.dll
  Running tests: /Users/soheilalizadeh/Codes/dotnet/aspnetcore/artifacts/bin/Microsoft.AspNetCore.JsonPatch.Tests/Debug/net7.0/Microsoft.AspNetCore.JsonPatch.Tests.dll [net7.0|x64]
  Tests succeeded: /Users/soheilalizadeh/Codes/dotnet/aspnetcore/artifacts/bin/Microsoft.AspNetCore.JsonPatch.Tests/Debug/net7.0/Microsoft.AspNetCore.JsonPatch.Tests.dll [net7.0|x64]

Build succeeded.
    0 Warning(s)
    0 Error(s)

```

@rainersigwald
