### ISSUE TITLE
ArgumentNullException leading to a VS crash

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/msbuild#7453]
### Issue Description

Seeing an ANE crash while debugging VS, after creating a project.

Discovered while researching a hang reported in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1462801. Perhaps the failures are related.

### Steps to Reproduce

- Launch VS
- Start with no solution
- Add a text file (to create an empty solution)
- Add a new Console App
- See an exception that leads to a crash

### Analysis

```
System.ArgumentNullException: Parameter "packet" cannot be null.
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull(Object parameter, String parameterName, String resourceName)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProc.SendData(Int32 nodeId, INodePacket packet)
   at Microsoft.Build.BackEnd.NodeManager.SendData(Int32 node, INodePacket packet)
   at Microsoft.Build.BackEnd.SdkResolution.MainNodeSdkResolverService.PacketReceived(Int32 node, INodePacket packet)
   at Microsoft.Build.BackEnd.NodePacketFactory.PacketFactoryRecord.DeserializeAndRoutePacket(Int32 nodeId, ITranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, ITranslator translator)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.NodeContext.ReadAndRoutePacket(NodePacketType packetType, Byte[] packetData, Int32 packetLength)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.NodeContext.BodyReadComplete(IAsyncResult result)
   at System.IO.Pipes.PipeStream.AsyncPSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

The ANE originates here:

https://github.com/dotnet/msbuild/blob/9c173296404f9c365cc524569766f16d7cfcf308/src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs#L93

`response` will be null in the `finally` block if there was an exception. That null value triggers an exception, which crashes VS in the above scenario.

`#nullable enable` would flag this issue in the code.

### Versions & Configurations

VS 17.2.0 Preview 3.0 [32308.589.main]

**Comment by jeffkl** [comment]
I updated this code recently but this code path didn't change that much.  It used to run inside a throw away task.

https://github.com/dotnet/msbuild/blob/fb700f90493a0bf47623511edf28b1d6c114e4fa/src/Build/BackEnd/Components/SdkResolution/MainNodeSdkResolverService.cs#L152-L179

I wonder if its been throwing for a while?  If an exception is thrown, a "fatal build error" is logged, I wonder if we can get those exception details?

This code is handling a request from an out-of-proc node to get the path to an MSBuild project SDK.  The out-of-proc node is waiting for a response we need to send something back I think.  I really want to know what the exception is...

**Comment by drewnoakes** [comment]
@jeffkl it should be easy enough to repro with the above steps. Let me know if it doesn't repro for you and we can take a loon on my machine.

**Comment by jeffkl** [comment]
Interesting yeah it repros on 17.1.0 at least which means its not a _regression_ from my recent change.  Still not great obviously but it seems like the problem has been around for a while.

I tried debugging my local experimental instance which repro'd the problem but didn't see the exception, how do I get this to happen in a debugger? This is what I tried:

* Launch local VS
* Launch Experimental instance
* Attach VS to experimental instance
* Load symbols for MSBuild assemblies
* Configure debugger to break on ArgumentNullException
* Repro problem in experimental instance

**Comment by jeffkl** [comment]
@BenVillalobos when working on a fix I realized that this is fallout from https://github.com/dotnet/msbuild/pull/6763 which technically is incomplete since it now throws an exception on the main node when an out-of-proc node is requesting SDK resolution.  Should the fix be to serialize the `SDKResolverException` back to the out-of-proc node and throw it there?  Otherwise the current APIs only let me send back an error message to the out-of-proc node.  😡

**Comment by ArsiIksait** [comment]
I also encountered an ArgumentNullException when I was building a .NET Aspire project using the tool aspirate:

![image](https://github.com/user-attachments/assets/68b0ef47-9efc-43b5-be34-5d7a02960545)

```
PS C:\Users\32512\source\repos\LiveMusicProjectX\AspireApp.AppHost> aspirate.exe init

     _                    _           ___
    / \     ___   _ __   (_)  _ __   ( _ )
   / _ \   / __| | '_ \  | | | '__|  / _ \
  / ___ \  \__ \ | |_) | | | | |    | (_) |
 /_/   \_\ |___/ | .__/  |_| |_|     \___/
                 |_|
Handle deployments of a .NET Aspire AppHost


── Handle Initialization Defaults ──────────────────────────────────────────────────────────────────────────────────────
(?) Done: Set 'Container builder' to 'docker'.
Aspirate supports setting a fall-back value for projects that have not yet set a 'ContainerRegistry' in their csproj
file.
Would you like to set a fall-back value for the container registry? [y/n] (n): n
Aspirate supports setting a repository prefix for all for projects.
Would you like to set this value? [y/n] (n): n
(?) Done: Set 'Container fallback tag' to 'latest'.
Aspirate supports setting a custom directory for 'Templates' that are used when generating kustomize manifests.
Would you like to use a custom directory (selecting 'n' will default to built in templates ? [y/n] (n): n
(?) Done: Configuration for aspirate has been bootstrapped successfully at
'C:\Users\32512\source\repos\LiveMusicProjectX\AspireApp.AppHost\.\aspirate.json'.

 ?? Execution Completed ??
PS C:\Users\32512\source\repos\LiveMusicProjectX\AspireApp.AppHost> aspirate generate

     _                    _           ___
    / \     ___   _ __   (_)  _ __   ( _ )
   / _ \   / __| | '_ \  | | | '__|  / _ \
  / ___ \  \__ \ | |_) | | | | |    | (_) |
 /_/   \_\ |___/ | .__/  |_| |_|     \___/
                 |_|
Handle deployments of a .NET Aspire AppHost


── Handling Aspirate State ─────────────────────────────────────────────────────────────────────────────────────────────

── Handling Aspirate Secrets ───────────────────────────────────────────────────────────────────────────────────────────
Secrets are to be protected by a password

Please enter new Password: *
Please enter it again to confirm: *
Secret State has been initialised!.

── Handling Configuration ──────────────────────────────────────────────────────────────────────────────────────────────
Successfully loaded existing aspirate bootstrap settings from '.'.

── Handling Aspire Manifest ────────────────────────────────────────────────────────────────────────────────────────────
Generating Aspire Manifest for supplied App Host
(?) Done:  Created Aspire Manifest At Path:
C:\Users\32512\source\repos\LiveMusicProjectX\AspireApp.AppHost\manifest.json

── Selecting Required Components ───────────────────────────────────────────────────────────────────────────────────────

── Handling Aspire Dashboard ───────────────────────────────────────────────────────────────────────────────────────────
Would you like to deploy the aspire dashboard and connect the OTLP endpoint? [y/n] (y): y

── Handling Inputs ─────────────────────────────────────────────────────────────────────────────────────────────────────

── Handle Value and Parameter Substitution ─────────────────────────────────────────────────────────────────────────────

── Handling DAPR Components ────────────────────────────────────────────────────────────────────────────────────────────
No Dapr components selected, skipping Dapr annotations.

── Gathering Information about deployables ─────────────────────────────────────────────────────────────────────────────
Gathering container details for each project in selected components
(?) Done:  Populated container details cache for project livemusicserver
Gathering Tasks Completed - Cache Populated.

── Handling Projects ───────────────────────────────────────────────────────────────────────────────────────────────────
Building all project resources, and pushing containers

Executing: dotnet publish
"C:\Users\32512\source\repos\LiveMusicProjectX\AspireApp.AppHost\../LiveMusicServer/LiveMusicServer.csproj"
-t:PublishContainer --verbosity "quiet" --nologo -r "linux-x64" -p:ContainerRepository="livemusicserver"
-p:ContainerImageTag="latest"
MSBUILD : error MSB4166:
瀛愯妭鐐光€?鈥濊繃鏃╅€€鍑恒€傛鍦ㄥ叧闂€傚彲浠ュ湪鈥淐:\Users\32512\AppData\Local\Temp\MSBuildTemp\鈥濅腑鐨勬枃浠朵腑鎵
惧埌璇婃柇淇℃伅锛屽苟灏嗗叾鍛藉悕涓?MSBuild_*.failure.txt銆傞€氳繃灏?MSBUILDDEBUGPATH
鐜鍙橀噺璁句负鍏朵粬鐩綍锛屽彲鏇存敼姝や綅缃€?
MSBUILD : error MSB4166:
C:\Users\32512\AppData\Local\Temp\MSBuildTemp\MSBuild_pid-11684_35201d88d2ef435f91e00de445495441.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 11684:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 2024/8/30 4:04:33
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe,
Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent
localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:

鏈夊彲鐢ㄧ殑宸ヤ綔璐熻浇鏇存柊銆傛湁鍏宠缁嗕俊鎭紝璇疯繍琛?`dotnet workload list`銆?
(1): Aspirate will now exit.
```

```
UNHANDLED EXCEPTIONS FROM PROCESS 9072:
=====================
2024/8/30 4:04:55
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
   at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```

**Comment by rainersigwald** [comment]
@ArsiIksait can you update your .NET SDK? That crash should be fixed by https://github.com/dotnet/msbuild/pull/10464.

**Comment by ArsiIksait** [comment]
@rainersigwald How do I update my .NET SDK? Is it from https://dotnet.microsoft.com/zh-cn/download Install .NET SDK 8.0.401? Or do I need to build this project myself?
![image](https://github.com/user-attachments/assets/d8404a57-4a3b-4fc4-83d1-6ea224cd8f03)

**Comment by ArsiIksait** [comment]
@rainersigwald Thank you, this problem was solved after I updated it, but then a new problem appeared, I don't know what's happening

```
Executing: dotnet publish
"C:\Users\32512\source\repos\AspireApp.AppHost\../AspireApp.ApiService/AspireApp.ApiService.csproj" -t:PublishContainer
--verbosity "quiet" --nologo -r "linux-x64" -p:ContainerRepository="apiservice" -p:ContainerImageTag="latest"
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:
鈥淐reateNewImage鈥濅换鍔℃剰澶栧け璐ャ€?[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:
System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32
estimatedSize) [C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IV
alueTaskSource<TResult>.GetResult(Int16 token)
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IV
alueTaskSource<TResult>.GetResult(Int16 token)
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
System.Net.Http.HttpConnection.FillAsync(Boolean async)
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32
bufferSize, CancellationToken cancellationToken)
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken
cancellationToken) [C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
Microsoft.NET.Build.Containers.Registry.DownloadBlobAsync(String repository, Descriptor descriptor, CancellationToken
cancellationToken) in /_/src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs:line 337
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
Microsoft.NET.Build.Containers.DockerCli.WriteImageToStreamAsync(BuiltImage image, SourceImageReference sourceReference,
DestinationImageReference destinationReference, Stream imageStream, CancellationToken cancellationToken) in
/_/src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs:line 282
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
Microsoft.NET.Build.Containers.DockerCli.LoadAsync(BuiltImage image, SourceImageReference sourceReference,
DestinationImageReference destinationReference, CancellationToken cancellationToken) in
/_/src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs:line 104
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
Microsoft.NET.Build.Containers.Tasks.CreateNewImage.PushToLocalRegistryAsync(BuiltImage builtImage, SourceImageReference
sourceImageReference, DestinationImageReference destinationImageReference, Telemetry telemetry, CancellationToken
cancellationToken) in /_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs:line 218
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
Microsoft.NET.Build.Containers.Tasks.CreateNewImage.ExecuteAsync(CancellationToken cancellationToken) in
/_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs:line 182
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
Microsoft.NET.Build.Containers.Tasks.CreateNewImage.Execute() in
/_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs:line 36
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]
C:\Program Files\dotnet\sdk\8.0.401\Containers\build\Microsoft.NET.Build.Containers.targets(242,5): error MSB4018:    at
Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext
taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
[C:\Users\32512\source\repos\AspireApp.ApiService\AspireApp.ApiService.csproj]

鏈夊彲鐢ㄧ殑宸ヤ綔璐熻浇鏇存柊銆傛湁鍏宠缁嗕俊鎭紝璇疯繍琛?`dotnet workload list`銆?
(1): Aspirate will now exit.

```

**Comment by YuliiaKovalova** [comment]
It looks like the issue was resolved. 
Feel free to open a new one if you see it again.
