### ISSUE TITLE
MSBuild node crash at Microsoft.Build.Collections.RetrievableEntryHashSet`1.Enumerator.MoveNext()

### ISSUE THREAD

**Issue by AArnott** [dotnet/msbuild#7779]
### Issue Description

MSBuild crashed during a VS build.

### Steps to Reproduce

I just did Ctrl-F5 in a vsix project twice in a row. I do this regularly. The second time probably should have been recognized as an up-to-date build and skipped, but it didn't. That's usually ok too, but this time msbuild crashed.

### Expected Behavior

A successful build.

### Actual Behavior

The output window had this:

```
1>MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\andarno\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
1>MSBUILD : error MSB4166: C:\Users\andarno\AppData\Local\Temp\MSBuild_pid-88828_d6d1b9e149eb4a848168eef5cf75083e.failure.txt:
1>MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 88828:
1>MSBUILD : error MSB4166: =====================
1>MSBUILD : error MSB4166: 7/1/2022 11:26:12 AM
1>MSBUILD : error MSB4166: System.InvalidOperationException: Operation is not valid due to the current state of the object.
1>MSBUILD : error MSB4166:    at Microsoft.Build.Collections.RetrievableEntryHashSet`1.Enumerator.MoveNext()
1>MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.Logging.ProjectLoggingContext.<FilterEnvironmentDerivedProperties>d__3.MoveNext()
1>MSBUILD : error MSB4166:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
1>MSBUILD : error MSB4166:    at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
1>MSBUILD : error MSB4166:    at Microsoft.Build.Framework.ProjectStartedEventArgs.WriteToStream(BinaryWriter writer)
1>MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
1>MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
1>MSBUILD : error MSB4166: ===================
1>MSBUILD : error MSB4166: 
1>MSBUILD : error MSB4166: 
```

### Versions & Configurations

VS 17.3-preview.3 (32629.440.main)

**Comment by rainersigwald** [comment]
Should be fixed by #7766 in the next Int Preview build. To work around, you should be able to disable the Project System Tools VS extension.
