### ISSUE TITLE
Unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE

### ISSUE THREAD

**Issue by ssa3512** [dotnet/msbuild#7858]
Increasing number of builds failing on Azure DevOps agents with this message. Any help that can be provided would be great.

```
##[error]This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled.
    System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__51.MoveNext() [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext() [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext() [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext() [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext() [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext() [D:\a\1\s\Source\AOS.ServiceImplementation.Payroll.FrontEnd\AOS.ServiceImplementation.Payroll.FrontEnd.csproj]
```

**Comment by rainersigwald** [comment]
Unfortunately an `OutOfMemoryException` can be tricky to chase down, since the codepath where it is thrown is not necessarily where most of the memory is allocated.

Can we start by describing your build more?

* What is your codebase like?
* What version of MSBuild/Visual Studio/dotnet are you using to build?
* Can you observe passing builds? How much memory are they using?

**Comment by ssa3512** [comment]
> Can we start by describing your build more?

Codebase is a relatively large solution, 132 projects at the moment. The majority are new style (`<Project Sdk="Microsoft.NET.Sdk">)` style targeting `netstandard2.0` or dual targeting `netstandard2.0` and `netstandard2.1`
38 of the projects are MSTest unit tests targeting net472 and/or net6.0

There are seven old style projects targeting .NET Framework including the one referenced in the error message. These are the very top level application projects.

There are also four top level application projects for Azure Functions, targeting net6.0.

We are using the Azure DevOps `windows-latest` image, which is VS 2022. We are passing the following flags to the build task which is Azure DevOps task `VSBuild@1`:
`/m /p:PackageLocation=$(build.binariesdirectory) /p:GeneratePackageOnBuild=true`

I don't believe Azure DevOps has any way for us to observe the build memory usage.

**Comment by rainersigwald** [comment]
@ssa3512 can you try switching to the 64-bit MSBuild via `VSBuild`'s `msbuildArchitecture: 'x64'` argument? That's usually the cheapest/easiest way out of OOM problems.

That solution size by itself shouldn't be a big problem; we regularly build repos with thousands of projects.

**Comment by ssa3512** [comment]
@rainersigwald Thanks, I wasn't aware of that argument. I am updating our pipeline now and will report back if that helps out.

**Comment by ssa3512** [comment]
We haven't had any failures since I added the x64 parameter so I think that solved the issue. Thanks so much.

**Comment by rainersigwald** [comment]
Awesome! Please let us know if it doesn't hold out.
