### ISSUE TITLE
MSBuild version 17.4.0 does not Build.

### ISSUE THREAD

**Issue by vlukyanau** [dotnet/msbuild#8158]
It does not happen on 17.3.6.
MSBuild version 17.4.0+18d5aef85 for .NET Framework
17.4.0.51802

```
C:\Users\User\.nuget\packages\bridge.min\17.10.1\build\Bridge.Min.targets(25,5): error : 2022-11-11T20:24:07:240       Error           Cannot add nested type as the type
'MyLib1, Version=2.4.3.0, Culture=neutral, PublicKeyToken=null:Microsoft.CodeAnalysis.EmbeddedAttribute' is duplicated with 'MyLib2, Version=2.4.3.0, Culture=neutral, PublicKeyToken=null:Microsoft.CodeAnalysis.EmbeddedAttribute'    at Bridge.Translator.Translator.AddNestedTypes(IEnumerable`1 types)
C:\Users\User\.nuget\packages\bridge.min\17.10.1\build\Bridge.Min.targets(25,5): error :    at Bridge.Translator.Translator.ReadTypes(AssemblyDefinition assembly)
C:\Users\User\.nuget\packages\bridge.min\17.10.1\build\Bridge.Min.targets(25,5): error :    at Bridge.Translator.Translator.InspectReferences()
C:\Users\User\.nuget\packages\bridge.min\17.10.1\build\Bridge.Min.targets(25,5): error :    at Bridge.Translator.Translator.Translate()
C:\Users\User\.nuget\packages\bridge.min\17.10.1\build\Bridge.Min.targets(25,5): error :    at Bridge.Build.BridgeCompilerTask.Execute()
```

**Comment by rainersigwald** [comment]
I think you'll have to take this up with the maintainers of the `Bridge.Min` package, unless you see some evidence that MSBuild has unexpectedly changed the inputs to the task somehow.
