### ISSUE TITLE
Skip Symlinks test on dev build when admin rights are missing

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8212]
### Problem

`Microsoft.Build.UnitTests.FileMatcherTest.DoNotFollowRecursiveSymlinks` is failing when user does not have `SeCreateSymbolicLinkPrivilege`
This needs elevation by default from win10 - so will fail for dev builds unless group poplicy is adjusted:

```
System.IO.IOException : A required privilege is not held by the client. : 'C:\\Users\\jankrivanek\\AppData\\Local\\Temp\\5yy3fcpf.40y\\MSBuildTempjankrivanek\\Temporarya9daa95a8d814ccfbbeb8fd96be54fa3\\subfolder\\mySymlink'
   at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
   at System.IO.Directory.CreateSymbolicLink(String path, String pathToTarget)
   at Microsoft.Build.UnitTests.FileMatcherTest.DoNotFollowRecursiveSymlinks() in C:\src\msbuild\src\Shared\UnitTests\FileMatcher_Tests.cs:line 80
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Proposed solution
Either fail more gracefully (add info about `SeCreateSymbolicLinkPrivilege` and remedy suggestion into test failure), or skip the test in non-CI builds when the needed permission is not available

**Comment by rainersigwald** [comment]
> This needs elevation by default from win10 - so will fail for dev builds unless group poplicy is adjusted:

This shouldn't be true; what OS version are you running? Windows has been relaxing security on symlink creation since I think win8.

**Comment by JanKrivanek** [comment]
https://github.com/xunit/xunit/issues/2073

**Comment by Forgind** [comment]
From when I introduced the change, it needed elevation on old versions of windows 10. It should be fine on windows 11.

The issue is that if we make it only run if you have admin privileges and/or SeCreateSymbolicLinkPrivilege, then it could theoretically be wrong (at least for most users), and they wouldn't even know. Indeed, this was true for creating symbolic links for quite a while.

I'll admit that goal is less important than "you should be able to run tests." My plan is to introduce a second test [here](https://github.com/dotnet/msbuild/pull/8149) that explicitly checks whether you can create a symbolic link and fails with a very clear error message if not. Does that sound sufficient, or do you think we need to make this test not fail in the first place on an old Windows OS?

**Comment by JanKrivanek** [comment]
User environment configuration test sounds good enough.

I'm just thinking if we might want to add mention of need of [Developer Mode](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development) into our Readme or Contributin guidelines?

**Comment by Forgind** [comment]
I don't think it actually requires developer mode; was there something else that requires it?

**Comment by rainersigwald** [comment]
@Forgind the docs on `CreateSymbolicLink` say you have to have developer mode enabled for `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` to do anything: https://learn.microsoft.com/windows/win32/api/winbase/nf-winbase-createsymboliclinka

**Comment by Forgind** [comment]
Ah; you are correct.
