### ISSUE TITLE
CombineTargetFrameworkInfoProperties fails with ArgumentNullException

### ISSUE THREAD

**Issue by marek-safar** [dotnet/msbuild#8320]
Extracted from https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/141116/logs/19

```
2023-01-18T13:41:58.9010353Z Msbuild failed when processing the file '/home/vsts/work/1/s/src/linker/Mono.Linker.csproj' with message: /home/vsts/work/1/s/.dotnet/sdk/8.0.100-alpha.1.23061.8/Microsoft.Common.CurrentVersion.targets: (1951, 5): The "CombineTargetFrameworkInfoProperties" task failed unexpectedly.
2023-01-18T13:41:58.9011595Z System.ArgumentNullException: Value cannot be null. (Parameter 'value')
2023-01-18T13:41:58.9012203Z    at System.ArgumentNullException.Throw(String paramName)
2023-01-18T13:41:58.9012847Z    at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
2023-01-18T13:41:58.9013426Z    at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
2023-01-18T13:41:58.9013984Z    at Microsoft.Build.Tasks.CombineTargetFrameworkInfoProperties.Execute()
2023-01-18T13:41:58.9017422Z    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2023-01-18T13:41:58.9018081Z    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

**Comment by marek-safar** [comment]
The stack trace was extracted from CI builds that were failing in case the log was removed.

The implementation has [disabled](https://github.com/dotnet/msbuild/blob/main/src/Tasks/CombineTargetFrameworkInfoProperties.cs#L8) nullable warnings and for the utility type [too](https://github.com/dotnet/msbuild/blob/main/src/Shared/EscapingUtilities.cs#L11) otherwise it'd be obvious what's wrong. However, it's still clear that [CombineTargetFrameworkInfoProperties](https://github.com/dotnet/msbuild/blob/main/src/Tasks/CombineTargetFrameworkInfoProperties.cs#L43) is not handling null case of `RootElementName`.

**Comment by rainersigwald** [comment]
Ok, then let's use this bug to track improving the debuggability of this situation.
