### ISSUE TITLE
OutOfMemoryException: Task 'GenerateAppxManifest' failed. Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/msbuild#8402]
Stumbled upon this crash with a 100% repro rate. I've narrowed it down to the following setup:

- A WinRT component project (ie. uap10.0 TFM, winmdobj output type)
- A partial method declaration
  - It can be static or not, and accessibility doesn't matter
  - It also doesn't matter if it's in a type that implements a COM/WinRT interface or not
- A source generator that implements that partial method

If you then build an app referencing this project, you get the following MSBuild crash:

```
Error		Task 'GenerateAppxManifest' failed. Array dimensions exceeded supported range.
Error		This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled.
    System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.MetadataReader.AttributeDecoder.ReadSerializedValue(ITypeReference type)
   at Microsoft.Cci.MetadataReader.CustomAttributeDecoder..ctor(PEFileToObjectModel peFileToObjectModel, MemoryReader signatureMemoryReader, UInt32 customAttributeRowId, IMethodReference attributeConstructor)
   at Microsoft.Cci.MetadataReader.PEFileToObjectModel.GetCustomAttributeAtRow(MetadataObject owningObject, UInt32 token, UInt32 customAttributeRowId)
   at Microsoft.Cci.MetadataReader.ObjectModelImplementation.MetadataObject.GetAttributes()
   at Microsoft.Cci.MetadataReader.ObjectModelImplementation.MetadataObject.get_Attributes()
   at Microsoft.Cci.MetadataTraverser.TraverseChildren(ITypeDefinitionMember typeMember)
   at Microsoft.Cci.MetadataTraverser.TraverseChildren(IMethodDefinition method)
   at Microsoft.Cci.MetadataTraverser.Traverse(IMethodDefinition method)
   at Microsoft.Cci.MetadataTraverser.Traverse(IEnumerable`1 methods)
   at Microsoft.Cci.MetadataTraverser.TraverseChildren(ITypeDefinition typeDefinition)
   at Microsoft.Cci.MetadataTraverser.Traverse(INamespaceTypeDefinition namespaceTypeDefinition)
   at Microsoft.Cci.MetadataTraverser.Traverse(IEnumerable`1 namespaceMembers)
   at Microsoft.Cci.MetadataTraverser.Traverse(INestedUnitNamespace nestedUnitNamespace)
   at Microsoft.Cci.MetadataTraverser.Traverse(IEnumerable`1 namespaceMembers)
   at Microsoft.Cci.MetadataTraverser.Traverse(INestedUnitNamespace nestedUnitNamespace)
   at Microsoft.Cci.MetadataTraverser.Traverse(IEnumerable`1 namespaceMembers)
   at Microsoft.Cci.MetadataTraverser.Traverse(IRootUnitNamespace rootUnitNamespace)
   at Microsoft.Cci.MetadataTraverser.Traverse(IAssembly assembly)
   at Microsoft.Build.AppxPackage.WinmdVisitor.Traverse(IAssembly assembly, Boolean swallowTraversalException)
   at Microsoft.Build.AppxPackage.WinmdVisitor.TraverseAssembly(IAssembly assembly, Boolean swallowTraversalException)
   at Microsoft.Build.AppxPackage.WinmdVisitor.Traverse(DefaultHost host, Boolean swallowTraversalException)
   at Microsoft.Build.AppxPackage.WinmdVisitor.ProcessInternal(AppxPackagingTaskHelper taskHelper, ITaskItem[] winmdFiles, ITaskItem[] nonFrameworkSdkReferences, ITaskItem[] sdkWinmdFiles, String managedWinmdInprocImplementation, Boolean harvestRegistrationInformation, Boolean loadMscorlibIntoHost, WinMdCacheOptions cacheOptions)
   at Microsoft.Build.AppxPackage.WinmdVisitor.Process(AppxPackagingTaskHelper taskHelper, ITaskItem[] winmdFiles, ITaskItem[] nonFrameworkSdkReferences, ITaskItem[] sdkWinmdFiles, String managedWinmdInprocImplementation, Boolean harvestRegistrationInformation, WinMdCacheOptions cacheOptions)
   at Microsoft.Build.AppxPackage.GenerateAppxManifest.UpdateWinmdRegistration()
   at Microsoft.Build.AppxPackage.GenerateAppxManifest.ProcessDocument()
   at Microsoft.Build.AppxPackage.GenerateAppxManifest.ExecuteImplementation()
   at Microsoft.Build.AppxPackage.AppxPackagingTaskHelper.Execute(String file)
   at Microsoft.Build.AppxPackage.AppxPackagingTaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<InitializeAndExecuteTask>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteBucket>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()
```

I'm happy to share additional info if needed (eg. logs or anything), though this happens in the Microsoft Store repo so I can't do so publicly. If there's anything else on my end that would help, feel free to ping me on Teams 🙂

**Comment by rainersigwald** [comment]
Can you please [open a Visual Studio feedback ticket](https://docs.microsoft.com/visualstudio/ide/feedback-options)? That has confidential-to-Microsoft-only options for sharing, and you should be able to upload high-fidelity logs/repro instructions.

After it's created, that will open an internal bug which will be routed to the right team. In this case, I think that's the Appx folks. If you post the link here we may be able to help that process go faster.

**Comment by Sergio0694** [comment]
Sweet, thank you! I've opened a ticket [here](https://developercommunity.visualstudio.com/t/MSBuild:-OutOfMemoryException:-Task-Gen/10270567?port=1025&fsid=036dac17-7df6-4395-89d7-77ec62d93bab) and included a full recording of compiling the project that causes the crash.
Hopefully that'll help 😊

**Comment by rainersigwald** [comment]
Perfect, thanks! We'll let that track it.
