### ISSUE TITLE
[Bug]: Assembly Microsoft.Build.Framework loaded twice

### ISSUE THREAD

**Issue by MansenC** [dotnet/msbuild#8514]
### Issue Description

Hey there,

I am currently trying to include MSBuild with my application. Unfortunately I deem that necessarry in favor of having users install the .NET SDK or Visual Studio. I've got that working in Visual Studio during debugging, here everything works fine.

My issue is, as the title says, tha Microsoft.Build.Framework gets loaded twice actually, into the same host context, that being the default one. I do not know if this issue is related to MSBuild directly or if it does have its root in the .NET runtime, but I'll try my luck here to see if there's any difference between my two environments in which this issue has its differences.

The reason I'm talking about two environments is that I am hosting the .NET application myself, I have a native host application that invokes the CoreCLR and runs my code, which in turn tries to invoke MSBuild. Running the code from that native host causes the issue to arise, and in my debugging environment which is started using Visual Studio I have no issues.

### Steps to Reproduce

Update: I have made a repository reproducing the issue. It is found [here](https://github.com/MansenC/TwiceLoadedAssemblyIssue). Note that this only works on Windows since I am using a Windows machine.

I am not quite sure if it is easily reproducible or if that even does help. I have not tested this thusfar, but I expect it goes as follows: Create a native host for some C# code that is "started" using hostfxr_initialize_for_dotnet_command_line_fn. In one of the calls to said C# code, start a build using the `BuildManager.DefaultBuildManager` (this is where the first assembly load occurrs), create a new `MSBuild.Project` instance (this is where the assembly gets loaded a second time), and then try to restore the project.

The restore fails here, due to the error message `WarnForInvalidProjectsTask could not be instantiated from assembly`. Now, don't be too excited, this is an error message that has arised before when there had been version conflicts between Visual Studio, MSBuild and ReSharper all using a different version of the `NuGet.Build.Tasks.dll` file. This is unfortunately not the case. I really suspect that the duplicated assembly is the root cause of this issue here.

### Expected Behavior

The restore task succeeds and no assembly is loaded twice

### Actual Behavior

The assembly gets loaded twice, and thus, no NuGet task can be casted to MSBuild.Framework.ITask

### Analysis

As stated above, I know where both assemblies get loaded. And it's quite odd. The first time the assembly gets loaded is implicitly through .Net - when the function gets called that starts my build, or in other words, the first time I use any class that in itself references the `Microsoft.Build.Framework` namespace and thus that DLL. The call is made through `System.Runtime.Loader.AssemblyLoadContext.Resolve` as expected, and this is the only time the DLL is loaded in Visual Studio, too. This is the correct call and the only call that should load this assembly.

The second time the assembly is loaded is from a call to `Microsoft.Build.Evaluation.Project..ctor`. When I construct the new instance of Project, the following stacktrace is produced when I listen on OnAssemblyLoad:
```
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.GetResolverTypes(Assembly assembly)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.LoadResolvers(String resolverPath, LoggingContext loggingContext, ElementLocation location, List`1 resolvers)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.LoadResolversFromManifest(SdkResolverManifest manifest, LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.GetResolvers(IList`1 resolversManifests, LoggingContext loggingContext, ElementLocation sdkReferenceLocation)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdkUsingResolversWithPatternsFirst(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.<>n__0(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.<>c__DisplayClass3_0.<ResolveSdk>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(ProjectRootElement xml, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection)
```
Unfortunately, it seems like GetExportedTypes is implemented in non-C# code, which means it doesn't come up in the stacktrace retreived by `Environment.StackTrace`. The assembly is the exact same. It doesn't equal in code since it's a new instance, but it's the same path, same name, same version, same everything. And this is bad.

I don't think there's any way to fix that per say in here, but since it doesn't happen when I use Visual Studio as the runtime environment, there has to be a difference somewhere that prevents this from happening, and maybe someone here has an idea what that difference may be

Update: I have now found out some new things. First of all, a low hanging fruit to check was if any environment variabels differ. They don't, or at least don't matter. Additionally I have gone ahead and modified the `Microsoft.Build.dll` to print what is happening following the stacktrace of the second load. `GetExportedTypes` gets called on the dll `Microsoft.Build.NuGetSdkResolver`.

### Versions & Configurations

I am using .NET Core 6.0.201 with Visual Studio 22 and the following MSBuild (-related) NuGet packages:
- Microsoft.Build.Locator 1.4.1
- Microsoft.Build.NuGetSdkResolver 5.11.0-rc.10
- Microsoft.Build.Runtime 17.3.2
- NuGet.Build.Tasks 6.5.0

All this on Windows 11 x64.

Thank you in advance

**Comment by MansenC** [comment]
Closing this here since this is not an issue with MSBuild but with the CoreCLR/hostfxr
