### ISSUE TITLE
[Bug]: msbuild binary logger generating excessive memory spike at end of build 

### ISSUE THREAD

**Issue by MarkOsborneMS** [dotnet/msbuild#8595]
### Issue Description

When running `msbuild /t:restore /bl` on a large repo we are running out of memory at the end of the build on a 64GB machine. We see a large spike in memory after the console output shows the build as complete, before the process terminates with an out of memory exception.

This is a regression for as we started seeing this behavior in 17.6 preview, but we did not see this behavior in VS 17.5.

### Steps to Reproduce

We have a large repo.

### Expected Behavior

Expect that we can complete restore build with less than 64GB of memory, we do not see a memory spike with VS 17.5.

MSBuild version 17.5.1+f6fdcf537 for .NET Framework
![Memory2](https://user-images.githubusercontent.com/15384700/227361811-2f95e072-dbc2-4799-9f04-e95ff2f1baf0.jpg)

### Actual Behavior

We are seeing a huge 30GB memory spike after the build completes and an out of memory exception.

MSBuild version 17.6.0-preview-23164-01+18fe51042 for .NET Framework

![Memory1](https://user-images.githubusercontent.com/15384700/227348869-81953c95-357d-4ca7-9e11-7e6f4d7fb9bc.jpg)

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:09:43.47
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Throwing from logger shutdown
=============
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent()
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()

 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent()
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()
   at Microsoft.Build.Evaluation.ProjectCollection.Dispose(Boolean disposing)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache, String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Throwing from logger shutdown
=============
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent()
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()

 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownComponent()
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.Evaluation.ProjectCollection.ShutDownLoggingService()
   at Microsoft.Build.Evaluation.ProjectCollection.Dispose(Boolean disposing)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache, String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

### Analysis

Passing the additional parameter `/bl:ProjectImports=None` is a workaround for the issue, but not ideal as we prefer to collect complete binlogs from our build agents.

### Versions & Configurations

MSBuild version 17.6.0-preview-23164-01+18fe51042 for .NET Framework
17.6.0.16401

**Comment by KirillOsenkov** [comment]
GetAllBytes() grows a large memory stream in memory. 

This was introduced in https://github.com/dotnet/msbuild/commit/ec61b6fdf48021fca3e94d12ded473b25ca5db9b

cc @asklar

**Comment by KirillOsenkov** [comment]
@MarkOsborneMS after that build is done (crashed), there should still be the msbuild.binlog file on disk. Could you share it with me privately please.

**Comment by KirillOsenkov** [comment]
also if you could please share a successful binlog from the same large repo

**Comment by MarkOsborneMS** [comment]
@KirillOsenkov I have shared both binlogs with you privately.

**Comment by KirillOsenkov** [comment]
stats from the smaller (working) binlog:

![image](https://user-images.githubusercontent.com/679326/227644091-52534e5d-a217-4ea6-999b-5861de7b3ef4.png)

The size of the blob archive is 78 MB, I'm guessing using MemoryStream to write 78 MB pushes it over the limit due to array reallocations.

**Comment by KirillOsenkov** [comment]
In the smaller binlog, there are 600MB of files embedded:

![image](https://user-images.githubusercontent.com/679326/227646642-8489d87b-eb9f-4d09-9722-fffdefd4125c.png)

**Comment by KirillOsenkov** [comment]
you can save files from a binlog to a folder on disk using:

```
dotnet tool install -g binlogtool
binlogtool savefiles msbuildrestore175.binlog OutputFolder
```

**Comment by KirillOsenkov** [comment]
I took a look at the files and it's mostly 450 MB worth of project.assets.json files:
![image](https://user-images.githubusercontent.com/679326/227672246-1bd3c580-9a2f-43e4-bf42-ed955b70f70d.png)

**Comment by KirillOsenkov** [comment]
As a workaround, you can turn off embedding files into the binlog via:
`msbuild /bl:msbuild.binlog;ProjectImports=None`

**Comment by jeffkl** [comment]
> I took a look at the files and it's mostly 450 MB worth of project.assets.json files:

Does that seem like its the cause? Or do you think that should be okay and something else needs to be fixed?  I would expect the assets files to be highly compressible.

**Comment by KirillOsenkov** [comment]
Stats from the 770 MB binlog:

![image](https://user-images.githubusercontent.com/679326/227667766-93c3be45-5fee-413a-990c-2a90a599f065.png)

Again, mostly huge project.assets.json files, p2p.targets:
![image](https://user-images.githubusercontent.com/679326/227674897-882bc72f-ef68-4a83-a050-f1b730d78bc0.png)

**Comment by KirillOsenkov** [comment]
No, it's fine to embed the files. 

This logic starts breaking at this volume of data:
https://github.com/dotnet/msbuild/commit/ec61b6fdf48021fca3e94d12ded473b25ca5db9b#diff-0864a6f2e10a87d935fbf19d81370f534e67f33931642dec1f30023b108e2cdcR180

We need to stream the ProjectImports.zip into the binlog writer, instead of using File.ReadAllBytes(). It just chokes reallocating byte arrays growing the underlying memory stream.

I was just looking at the binlogs to understand if there are any abnormally large files that shouldn't have been included, but it just seems that the repo is huge, so nothing abnormal. It just crossed some threshold recently where the size became so big that it started OOMing.

**Comment by KirillOsenkov** [comment]
Here, we need to change this to return a Stream instead of a byte array:
https://github.com/dotnet/msbuild/blob/e7de1330724224a542668e1ef82c997613c7080c/src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs#L40

and add an API in the writer to write a stream instead of a byte array. Then we'll avoid reading the entire 500 MB into a MemoryStream to get the byte array, only to write it into the primary binlog stream again. Will probably need to pass the exact size in bytes, since the blob record writes the length first.

**Comment by KirillOsenkov** [comment]
@marcpopMSFT I'm unassigning myself, I've left instructions in the comment above about what the problem is and how to fix it. Hopefully you can find a volunteer. I'd be happy to code review the PR.

**Comment by KirillOsenkov** [comment]
Hmm, the crash is actually running out of memory in ZipArchive.Dispose():

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.Build.Logging.ProjectImportsCollector.Close(Boolean closeStream)
   at Microsoft.Build.Logging.ProjectImportsCollector.GetAllBytes()
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
```

This is not exactly what I thought, we aren't even getting to File.ReadAllBytes(). Is the ZipArchive being written into a MemoryStream? Why? We should be writing it to disk I think. 

https://github.com/dotnet/msbuild/pull/5718 will have more clues.

**Comment by KirillOsenkov** [comment]
Oh, I remember now, the problem was the temporary file ProjectImports.zip was messing up various scenarios. Should that file be in the temp directory instead?

**Comment by KirillOsenkov** [comment]
Still need to avoid the ReadAllBytes() as I wrote earlier.

**Comment by asklar** [comment]
right, the original change was to avoid creating a temporary file that was being picked up by various tools that have filesystem watchers (metro, defender, etc.), so the idea was to not create a temporary file if we're going to embed the zip in the binlog anyway.

note that in the non-embed case, before the change, we were reading the whole thing too:
https://github.com/dotnet/msbuild/pull/5718/files#diff-0864a6f2e10a87d935fbf19d81370f534e67f33931642dec1f30023b108e2cdcL188

so I'm not sure how this would have worked before this change, maybe we were getting lucky with memory fragmentation?

**Comment by KirillOsenkov** [comment]
Yup, we were just getting lucky. Not blaming your change, it was a good fix. Just started seeing some really huge builds and it became a problem. I think if we can get a safe temp file location, unique per process, we should write to that instead of the memory stream. Definitely shouldn't be creating any files in the source directory.

**Comment by asklar** [comment]
yeah, agree that a low-risk fix would be to revert the original change, store the zip in a temp location, and then only if we're not embedding it, move the temp file to the source directory (to preserve prior behavior). if we are embedding it, just read it via streams (not byte[]), then delete the temporary zip.

**Comment by MarkOsborneMS** [comment]
We just hit this after upgrading our pipelines to 17.6 GA

**Comment by MichalPavlik** [comment]
Hello, could you please share a link of your pipeline? Or some run where the embedding wasn't disabled? Thanks.

**Comment by MarkOsborneMS** [comment]
The failing builds have expired, and we added ProjectImports=None as a workaround in the pipeline.
