### ISSUE TITLE
[Infra]: CanShutdownServerProcess test is fleaky 

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8631]
### Issue Description

The `CanShutdownServerProcess` fails every now an then:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/3809076/229848999-dd5495f0-bf37-4187-b9db-d071426ca8bf.png">

not too often to be easily caught, but often enough to fail considerable number of PRs (hence already worth a dedicated item)

### Details

```
Error message
Shouldly.ShouldAssertException : False\n    should be\nTrue\n    but was not

Stack trace
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual)
   at Microsoft.Build.Engine.UnitTests.MSBuildServer_Tests.CanShutdownServerProcess(Boolean byBuildManager) in /home/vsts/work/1/s/src/MSBuild.UnitTests/MSBuildServer_Tests.cs:line 247
   at InvokeStub_MSBuildServer_Tests.CanShutdownServerProcess(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Sample run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=227421&view=ms.vss-test-web.build-test-results-tab&runId=4282826&resultId=100005&paneView=debug

**Comment by rokonec** [comment]
This has already been investigated in https://github.com/dotnet/msbuild/pull/8378
Special logging has been added to capture this eluding flaky test, but since it is stored in artifacts and test results, retry will overwrite both. 
So if I can ask, next time you will see it, do not retry before you copy aside related test artifacts and logs. Than please let me know and I will check it out.

**Comment by rokonec** [comment]
hopefully fixed
