### ISSUE TITLE
BinaryLoggerTests.BinaryLoggerShouldEmbedSymlinkFilesViaTaskOutput failure

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#8643]
So far I've seen this only once in #8632 on 4deecfc2 on Windows: https://dev.azure.com/dnceng-public/public/_build/results?buildId=227836&view=ms.vss-test-web.build-test-results-tab&runId=4295098&resultId=101767&paneView=debug

```
Shouldly.ShouldAssertException : zipArchive.Entries\n    should contain an element satisfying the condition\nzE.Name.EndsWith(&quot;testtaskoutputfile.txt&quot;)\n    but does not

   at Shouldly.ShouldBeEnumerableTestExtensions.ShouldContain[T](IEnumerable`1 actual, Expression`1 elementPredicate, Func`1 customMessage)
   at Shouldly.ShouldBeEnumerableTestExtensions.ShouldContain[T](IEnumerable`1 actual, Expression`1 elementPredicate)
   at Microsoft.Build.UnitTests.BinaryLoggerTests.BinaryLoggerShouldEmbedSymlinkFilesViaTaskOutput() in D:\a\1\s\src\Build.UnitTests\BinaryLogger_Tests.cs:line 324
```

**Comment by jrdodds** [comment]
Microsoft.Build.UnitTests.BinaryLoggerTests.BinaryLoggerShouldEmbedSymlinkFilesViaTaskOutput

This test failed for me today in a PR build. See build [20230412.4](https://dev.azure.com/dnceng-public/public/_build/results?buildId=236256&view=results).

**Comment by rainersigwald** [comment]
Unfortunately I think we need #8653 to get more info. Should be able to merge that tomorrow-ish.
