### ISSUE TITLE
[Bug]: incremental builds on osx-arm64 hang

### ISSUE THREAD

**Issue by lambdageek** [dotnet/msbuild#8754]
### Issue Description

When building https://github.com/dotnet/runtime on an arm64 mac, sometimes I get into situations where MSBuild will seemingly hang forever.  Running `killall dotnet` or doing the builds with `-nr:false` resolves the issue.

### Steps to Reproduce

1. Checkout https://github.com/dotnet/runtime/commit/ca6ab3227df73963d0d1b26f27063f2b2df5ee0d on an arm64 mac
2. `./build.sh --os browser -c Debug`
3. `src/tasks/WasmAppBuilder/WasmAppBuilder.cs`
4. `./build.sh --os browser -c Debug`

### Expected Behavior

The incremental build takes a few seconds

### Actual Behavior

The incremental build hangs for tens of minutes.

### Analysis

If I hit ctrl-C on an apparently hung build, it often is in the `Copy` task

```
/Users/alklig/work/dotnet-runtime/runtime/src/mono/llvm/llvm-init.proj(89,5): error MSB4018: The "Copy" task failed unexpectedly.
/Users/alklig/work/dotnet-runtime/runtime/src/mono/llvm/llvm-init.proj(89,5): error MSB4018: System.Threading.Tasks.TaskCanceledException: A task was canceled.
/Users/alklig/work/dotnet-runtime/runtime/src/mono/llvm/llvm-init.proj(89,5): error MSB4018:    at Microsoft.Build.Tasks.Copy.CopyParallel(CopyFileWithState copyFile, Int32 parallelism, List`1& destinationFilesSuccessfullyCopied)
/Users/alklig/work/dotnet-runtime/runtime/src/mono/llvm/llvm-init.proj(89,5): error MSB4018:    at Microsoft.Build.Tasks.Copy.Execute(CopyFileWithState copyFile, Int32 parallelism)
/Users/alklig/work/dotnet-runtime/runtime/src/mono/llvm/llvm-init.proj(89,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
/Users/alklig/work/dotnet-runtime/runtime/src/mono/llvm/llvm-init.proj(89,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

Some patches to dotnet/runtime to do less copying appears to alleviate the problem.

--- 

Additionally in some circumstances https://gitlab.kitware.com/cmake/cmake/-/issues/22372 macOS seems to dislike executing native binaries that are being copied around.  It's not clear if this is related to the issue we're experiencing.  But I just want to highlight that macOS is doing more work than one might expect when copying is going on.

### Versions & Configurations

Here's my `./dotnet.sh --info`

<details>
<pre>
 ./dotne
t.sh --info
.NET SDK:
 Version:   8.0.100-preview.3.23178.7
 Commit:    e300b0e1e6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-preview.3.23178.7/

.NET workloads installed:
 [maui-maccatalyst]
   Installation Source: SDK 8.0.100-preview.3
   Manifest Version:    8.0.0-preview.3.8149/8.0.100-preview.3
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100-preview.3/microsoft.net.sdk.maui/WorkloadManifest.json
   Install Type:        FileBased
 [maccatalyst]
   Installation Source: SDK 8.0.100-preview.3
   Manifest Version:    16.2.462-net8-p3/8.0.100-preview.3
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100-preview.3/microsoft.net.sdk.maccatalyst/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.0-preview.3.23174.8
  Architecture: arm64
  Commit:       47bad717bd

.NET SDKs installed:
  6.0.404 [/usr/local/share/dotnet/sdk]
  6.0.406 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]
  7.0.201 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.1.23115.2 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.2.23157.25 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.3.23178.7 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.1.23112.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.2.23153.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.3.23177.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.1.23110.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.2.23128.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23174.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/alklig/work/dotnet-runtime/runtime/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</pre>
</details>

**Comment by AR-May** [comment]
I was unable to reproduce this issue on my M1 Mac machine. 
Unassigning since I have no availability to hunt this bug. The team may return to it once we get hands on arm64 mac.
