### ISSUE TITLE
Flaky test - MSBuildServerTest

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8956]
### Context

```
System.TimeoutException : Test failed due to timeout: process 18281 is active for more than 30 sec.
```

```
   at Microsoft.Build.UnitTests.Shared.RunnerUtilities.RunProcessAndGetOutput(String process, String parameters, Boolean& successfulExit, Boolean shellExecute, ITestOutputHelper outputHelper) in /Users/runner/work/1/s/src/UnitTests.Shared/RunnerUtilities.cs:line 110
   at Microsoft.Build.UnitTests.Shared.RunnerUtilities.ExecMSBuild(String pathToMsBuildExe, String msbuildParameters, Boolean& successfulExit, Boolean shellExecute, ITestOutputHelper outputHelper) in /Users/runner/work/1/s/src/UnitTests.Shared/RunnerUtilities.cs:line 42
   at Microsoft.Build.Engine.UnitTests.MSBuildServer_Tests.MSBuildServerTest() in /Users/runner/work/1/s/src/MSBuild.UnitTests/MSBuildServer_Tests.cs:line 121
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

e.g.: https://dev.azure.com/dnceng-public/public/_build/results?buildId=320229&view=ms.vss-test-web.build-test-results-tab&runId=6566008&resultId=100002&paneView=debug

Looking on the history of the test it seems to fail almost 1 PR a day

**Comment by donJoseLuis** [comment]
@JanKrivanek should flaky tests be offlined until their reliability is stable?

**Comment by JanKrivanek** [comment]
> @JanKrivanek should flaky tests be offlined until their reliability is stable?

Ideally yes.
For now I'd leave the decision up on whoever will be investigating (as they migh need some diag data from CI). If the test still keeps hitting PRs in ~2 weeks, I'll disable it

**Comment by AR-May** [comment]
Team triage: Let's disable the test if it hits a lot of PRs per week.

**Comment by GangWang01** [comment]
For the following step, executing the build task that sleeps 100 seconds randonly timed out.
https://github.com/dotnet/msbuild/blob/93d8322d3e0265a0a527a6c2c8dfa6ba5a9d8e38/src/MSBuild.UnitTests/MSBuildServer_Tests.cs#L108-L123

It intended to let the build task (that made the started msbuild process definitely timeout after 30 seconds) use the old server process and terminate the build task through killing the old server process.
Most likely it didn't sleep enough time waiting for the build task to start and killed the old server process too fast. This resulted in the build started a new server process, and then the started msbuild process timed out after 30 seconds becuase of the build task sleeping 100 seconds.
