### ISSUE TITLE
Crash handler relies on BinaryFormatter?

### ISSUE THREAD

**Issue by kg** [dotnet/msbuild#9013]
I had some sort of msbuild failure occur during a source build of dotnet/runtime (probably my fault), but I noticed that the crash handler seems to try and serialize state with BinaryFormatter, which no longer works because support for it has been removed in 8 (afaik).

```
MSBUILD : error MSB4166: Child node "6" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTempkate/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: Child node "3" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTempkate/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: /tmp/MSBuildTempkate/MSBuild_pid-51284_8994c4b322254f82b048929a6b247fd4.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 51284:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 7/11/2023 4:43:18 PM
MSBUILD : error MSB4166: System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
MSBUILD : error MSB4166:    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.TranslateException(Exception& value)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildResult.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166: 
MSBUILD : error MSB4166: 
MSBUILD : error MSB4166: /tmp/MSBuildTempkate/MSBuild_pid-51195_ccd0543cc1b14867b276dfa044ac3e98.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 51195:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 7/11/2023 4:43:18 PM
MSBUILD : error MSB4166: System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
MSBUILD : error MSB4166:    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.TranslateException(Exception& value)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildResult.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================

```

**Comment by rainersigwald** [comment]
Do you know what SHA of MSBuild was involved there? I hope this was fixed by #8779.

cc @JanKrivanek

**Comment by kg** [comment]
Would have been dotnet/runtime main as of the 10th or 11th.

**Comment by rainersigwald** [comment]
Hmm, looks like runtime is on preview 5 (which shouldn't have the problem, because binaryformatter wasn't disabled then), so I'm wondering if a private just-built runtime was maybe applied with the preview-5 MSBuild bits? The fix we put in for preview 6 (https://github.com/dotnet/sdk/pull/33227) should work in that case (by opting into backward-compatibility). And then in preview 7 we shouldn't need it on this codepath any more.

So I'm hopeful that there's no current bug here. Sorry you ran into this though!

**Comment by kg** [comment]
How do I check which version of msbuild main is using? I had a crash during build again, but this time it didn't put any failure info in the temp directory. I nuked my .dotnet before building so it should be using the latest as far as dotnet/runtime is configured.

Here's the output from when it generated .dotnet:
```
kate@reeir-debian2:~/Projects/dotnet-runtime-wasm$ ./build.sh -c Release --os Browser /p:WasmNativeStrip=false
Downloading 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh'
  Attempting to install 'sdk v8.0.100-preview.6.23330.14' from public_location.
dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.100-preview.6.23330.14/dotnet-sdk-8.0.100-preview.6.23330.14-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.100-preview.6.23330.14/dotnet-sdk-8.0.100-preview.6.23330.14-linux-x64.tar.gz
dotnet-install: Installed version is 8.0.100-preview.6.23330.14
dotnet-install: Adding to current process PATH: `/home/kate/Projects/dotnet-runtime-wasm/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.

Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.100-preview.6.23330.14
```

**Comment by rokonec** [comment]
@JanKrivanek Is this still active?

**Comment by JanKrivanek** [comment]
This is fixed in NET 8
