### ISSUE TITLE
[Unhandled Exception]: System.OutOfMemoryException: Insufficient memory to continue the execution of the program - Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()

### ISSUE THREAD

**Issue by rmoreirao** [dotnet/msbuild#9025]
### Issue Description

We are trying to build a big solution (1K+ projects), and we are receiving the following exception - these are different builds, but it seems that the code is broken on the same place:

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()

System.AggregateException: One or more errors occurred. ---> Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Insufficient memory to continue the execution of the program.

System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()
```

### Steps to Reproduce

We are running the MSBuild from Azure DevOps Self-Hosted Agent on AKS Cluster using mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 base image. Using .Net Framework 4.6 on a x64 architecture.

The Node has 22GB and 6CPU core.

These are the MSBuild parameters: `msbuildArguments: '/p:RestoreLockedMode=true /p:GenerateBuildInfoConfigFile=false /p:RegisterForComInterop="false" /p:BuildInParallel="true" /nr:false /property:CopyRetryCount=20;CopyRetryDelayMilliseconds=2000 /verbosity:normal /nodeReuse:false'`

### Actual Behavior

**Example1:**

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.BackEnd.RequestBuilder.SaveOperatingEnvironment()
   at Microsoft.Build.BackEnd.RequestBuilder.<StartNewBuildRequests>d__61.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProjects>d__40.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskHost.<BuildProjectFilesInParallelAsync>d__84.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskHost.<InternalBuildProjects>d__80.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.MSBuild.<ExecuteTargets>d__80.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.MSBuild.<BuildProjectsInParallel>d__77.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.MSBuild.<ExecuteInternal>d__76.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<InitializeAndExecuteTask>d__24.MoveNext()
 End of stack trace from previous location where exception was thrown 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteBucket>d__19.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__51.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()
```

**Example2:**

```
System.AggregateException: One or more errors occurred. ---> Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: One or more errors occurred.

System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()
End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()

System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.RequestBuilder.WaitForCancelCompletion()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<CleanupForBuild>b__41_0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass72_0.<QueueAction>b__0()
---> (Inner Exception #0) Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Insufficient memory to continue the execution of the program.

System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()

 ---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables()
   at Microsoft.Build.BackEnd.RequestBuilder.ReportResultAndCleanUp(BuildResult result)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.RequestBuilder.WaitForCancelCompletion()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<CleanupForBuild>b__41_0()
   at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass72_0.<QueueAction>b__0()
```

### Analysis

It seems that this is a parallelism issue, when we move the parameter maxcpucount to 1, then the issue is not occurring.

### Versions & Configurations

MSBuild version 17.6.3+07e294721 for .NET Framework
17.6.3.22601

**Comment by JanKrivanek** [comment]
Interesting. There apparently historicaly was an allocations optimisation of involved code for win arch already: https://github.com/dotnet/msbuild/issues/2402

Would you be able to collect a dump of the crash, and if possible ETW trace of the build as well (`perfview collect /NoGui /Providers=*Microsoft-Build /BufferSize:8096 /CircularMB:8096 /NoNGenRundown /DataFile:oom-repro`) and share with us? (uploading to any internal share would do)

**Comment by JanKrivanek** [comment]
ETW needs to be collect from separate process, that will be started before the build and ctrl-c closed after the build. For ADO run, this might be more complicated. Can you consult your engineering services / infrastructure team on how to best provide crash dump and/or ETW trace from the build?

**Comment by rmoreirao** [comment]
Hi, yes.. In the end we figured out the if we use maxCpuCount=3 (even though we have 8 cores), then the problem is solved. But if we increase that, we start receive all kind of different errors. It was not only GetEnvironmentVariables - so we decided to keep it like this.

What do you think? Is this something it would still be worth exploring considering that we are receiving all different kind of errors? Or just let it like this?

Here is the other example:

UNHANDLED EXCEPTIONS FROM PROCESS 4512:
=====================
7/13/2023 1:54:06 PM
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.NET.Build.Tasks.TaskBase.LogErrorTelemetry(String eventName, Exception e)
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.NET.Build.Tasks.TaskWithAssemblyResolveHooks.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by AR-May** [comment]
Team triage: Does the issue ever happen on a developer machine? Unfortunately, without collecting more information (like dumps or ETW traces) we would not be able to figure out the reason of the failure.

**Comment by rmoreirao** [comment]
Hi, actually this is happening on Azure DevOps Agents - running on Windows 2019 Containers.

**Comment by JanKrivanek** [comment]
@rmoreirao Do you have an infrastructure team you can consult on collecting dumps from ADO?

I guess possibly setting some env vars to enable crash dump collection and setting the location (https://learn.microsoft.com/en-us/dotnet/core/diagnostics/collect-dumps-crash), and including the location to artifacts (regardless of success/error outcome of the run) might be a way forward here.

Based on the manifestation via different stack it's not actionable for us - but dumpwould greatly help in uncovering the real source of bloating.
