### ISSUE TITLE
[Bug]: Better and concise error message when project parameter has an invalid character like "."

### ISSUE THREAD

**Issue by pratikone** [dotnet/msbuild#9036]
### Issue Description

When passing project name parameter with "." in the project name, it errors out with the problem and doesn't suggest than an easy fix already exists where user can try-replacing it with "_". It should cover most common case of this error's occurrence. 
Secondly, the large wall of text due to stack traces is confusing too.

### Steps to Reproduce

I used msbuild and specified individual project to be built with `/t:foo.bar`. 
I get this large wall of error text
```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.ArgumentException: The name "foo.bar" contains an invalid character ".".
   at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectTargetElement.set_Name(String value)
   at Microsoft.Build.Construction.ProjectTargetElement.CreateDisconnected(String name, ProjectRootElement containingProject)
   at Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified, List`1 projectsInOrder)
   at Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified)
   at Microsoft.Build.Construction.SolutionProjectGenerator.Generate()
   at Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, BuildEventContext projectBuildEventContext, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass96_0.<IssueBuildRequestForBuildSubmission>g__IssueBuildSubmissionToSchedulerImpl|1(BuildSubmission submission, Boolean allowMainThreadBuild)

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.ArgumentException: The name "foo.bar" contains an invalid character ".".
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache, String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: System.ArgumentException: The name "foo.bar" contains an invalid character ".".
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache, String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

### Expected Behavior

One line of text which tells what error is and suggests a potential solution which is to replace `.` with `_`. 

### Actual Behavior

Large text of stack traces fill the screen.

### Analysis

This is not very helpful as : 
1. It is an easy solution to fix. The Microsoft docs [suggests](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-build-specific-targets-in-solutions-by-using-msbuild-exe?view=vs-2019#to-build-a-specific-target-of-a-specific-project-in-a-solution) to replace special character with a `_`. Why not suggest it in the error message ? 
2. The large wall of stack trace text makes it difficult to understand what the important error message it. The signal to noise ratio is very high.

**Comment by rainersigwald** [comment]
Wow, that's ugly. Looks like it's specific to specifying a target when building a solution--for an individual project the error is a much cleaner (though still a bit misleading)

```sh-session
$ ~/.dotnet/dotnet build src/Framework -t:foo.bar
MSBuild version 17.7.0+5785ed5c2 for .NET

  Determining projects to restore...
  All projects are up-to-date for restore.
/home/raines/src/msbuild/src/Framework/Microsoft.Build.Framework.csproj : error MSB4057: The target "foo.bar" does not exist in the project.
```

**Comment by pratikone** [comment]
Indeed. That's just downright misleading. Yeah, some good targeted error messages can do a lot to reduce frustration in using it.
