### ISSUE TITLE
[Bug]: MSBUILD : error MSB4166

### ISSUE THREAD

**Issue by SerendipitousTesselation** [dotnet/msbuild#9436]
### Issue Description

I'm hitting this issue with a UWP app. I'm reporting here as suggested by the docs page of MSB4166.

Output:
```
Build started...
1>------ Build started: Project: TestControlSample, Configuration: Debug x64 ------
1>MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\User\AppData\Local\Temp\MSBuildTempuser\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```
Contents of MSBuild_*.failure.txt:
```
UNHANDLED EXCEPTIONS FROM PROCESS 18652:
=====================
10/20/2023 3:21:36 PM
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServer()
   at System.IO.Pipes.NamedPipeServerStream.BeginWaitForConnection(AsyncCallback callback, Object state)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc()
===================
```

### Steps to Reproduce

I'm just F5-ing the solution/startup app.

Binary logs:
[MSBuildReproLogs.zip](https://github.com/dotnet/msbuild/files/13395072/MSBuildReproLogs.zip)

### Expected Behavior

The sample app deploys.

### Actual Behavior

build fails.

### Analysis

the compilation step seems to succeed.

### Versions & Configurations

MSBuild version 17.7.2+d6990bcfa for .NET Framework
17.7.2.37605

**Comment by SerendipitousTesselation** [comment]
There are, here it is:

[MSB4166_CrashDump.zip](https://github.com/dotnet/msbuild/files/13450629/MSB4166_CrashDump.zip)

**Comment by JanKrivanek** [comment]
Thank you for the data.
Couple points:
 * The rootcause is AV during obtaining call address into GenXbf. We sometimes see similar simptomps when Antivirus/Antimalware software is involved. It however usually has slightly different symptomps - Antivirus usually injects self into the MSBuild process and causes AV there (during calls that it deems unsafe) - in such cases we can see Antivirus module loaded into the MSBuild address space. I cannot see any suspicious module in this dump. Still - it might be good to check if you can repro on a different machine (without 3rd pty antivirus)
 * The crash happens in `windows.ui.xaml.build.tasks` module - @maddymontaquila, @AllenD-MSFT - I located you as owners of XamlCompiler in AzDO - would you be able to reassign or add to proper engineering contact?

The crashing stack:

```
 	genxbf.dll!XamlBinaryMetadataStore::GetXamlXmlNamespaceId(class std::shared_ptr<class XamlNamespace> const &,unsigned int &)	Unknown
 	genxbf.dll!XamlBinaryMetadataStore::GetXamlTypeId(class std::shared_ptr<class XamlType> const &,unsigned int &)	Unknown
 	genxbf.dll!XamlBinaryMetadataStore::GetXamlPropertyId(class std::shared_ptr<class XamlProperty> const &,class WinBluePropertyTypeCompatHelper const &,unsigned int &)	Unknown
 	genxbf.dll!XamlBinaryFormatSubWriter2::PersistProperty(class std::shared_ptr<class XamlProperty> const &)	Unknown
 	genxbf.dll!XamlBinaryFormatSubWriter2::PersistNode(class ObjectWriterNode const &)	Unknown
 	genxbf.dll!XamlBinaryFormatWriter2::ProcessSubNodes(class std::shared_ptr<class ObjectWriterNodeList> const &,class std::vector<unsigned int,class std::allocator<unsigned int> > &)	Unknown
 	genxbf.dll!XamlBinaryFormatWriter2::WriteAllNodes(class std::shared_ptr<class ObjectWriterNodeList> const &)	Unknown
 	genxbf.dll!XbfWriter::GetOptimizedBinaryEncodingFromReader(class std::shared_ptr<class XamlReader> const &,class std::shared_ptr<class ObjectWriterNodeList> const &,class std::array<unsigned char,64> const &,bool,unsigned int *,unsigned char * *)	Unknown
 	genxbf.dll!ProcessXamlText(unsigned char *,unsigned int,struct TargetOSVersion const &,bool,class std::array<unsigned char,64> const &,unsigned char * *,unsigned int *,unsigned int *,unsigned int *,unsigned int *)	Unknown
 	genxbf.dll!WriteImpl(struct IStream * *,unsigned int,struct IXbfMetadataProvider *,class std::vector<class std::array<unsigned char,64>,class std::allocator<class std::array<unsigned char,64> > > const &,struct TargetOSVersion const &,enum XbfGenerationFlags,struct IStream * *,unsigned int *,unsigned int *,unsigned int *,unsigned int *)	Unknown
 	genxbf.dll!Write()	Unknown
 	[External Code]	
>	Microsoft.Windows.UI.Xaml.Build.Tasks.dll!Microsoft.Windows.UI.Xaml.Build.Tasks.NativeMethodsHelper.Write(System.IntPtr dllHandle, System.Runtime.InteropServices.ComTypes.IStream[] xamlStreams, int numFiles, string[] pbChecksum, int checksumSize, Microsoft.Xaml.XBF.IXbfMetadataProvider provider, Microsoft.Xaml.XBF.TargetOSVersion targetVersion, uint xbfGenerationFlags, System.Runtime.InteropServices.ComTypes.IStream[] xbfStreams, out int errorCode, out int errorFileIndex, out int errorLine, out int errorColumn)	C#
 	Microsoft.Windows.UI.Xaml.Build.Tasks.dll!Microsoft.Xaml.XBF.XbfGenerator.GenerateXbfFromStreams(System.IntPtr dllHandle, System.Runtime.InteropServices.ComTypes.IStream[] inputStreams, System.Runtime.InteropServices.ComTypes.IStream[] outputStreams, uint xbfGenerationFlags, string[] checksums, Microsoft.Xaml.XBF.TargetOSVersion targetOS, out int errorCode, out int errorFile, out int errorLine, out int errorPosition)	C#
 	Microsoft.Windows.UI.Xaml.Build.Tasks.dll!Microsoft.Xaml.XBF.XbfGenerator.GenerateAll(System.IntPtr dllHandle, uint xbfGenerationFlags)	C#
 	Microsoft.Windows.UI.Xaml.Build.Tasks.dll!Microsoft.Xaml.XBF.XbfGenerator.GenerateXbfFiles(uint xbfGenerationFlags, bool v80Compat)	C#
 	Microsoft.Windows.UI.Xaml.Build.Tasks.dll!Microsoft.Windows.UI.Xaml.Build.Tasks.CompileXamlInternal.GenerateXbfFiles(System.Collections.Generic.IEnumerable<Microsoft.Xaml.XBF.IXbfFileNameInfo> xamlList)	C#
 	Microsoft.Windows.UI.Xaml.Build.Tasks.dll!Microsoft.Windows.UI.Xaml.Build.Tasks.CompileXamlInternal.DoExecute()	C#
 	Microsoft.Windows.UI.Xaml.Build.Tasks.dll!Microsoft.Windows.UI.Xaml.Build.Tasks.CompileXaml.Execute()	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask)	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.InitializeAndExecuteTask(Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.ItemBucket bucket, System.Collections.Generic.IDictionary<string, string> taskIdentityParameters, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask)	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask, System.Collections.Generic.Dictionary<string, string> lookupHash)	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup lookup)	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(Microsoft.Build.BackEnd.Logging.TargetLoggingContext loggingContext, Microsoft.Build.BackEnd.BuildRequestEntry requestEntry, Microsoft.Build.BackEnd.ITargetBuilderCallback targetBuilderCallback, Microsoft.Build.Execution.ProjectTargetInstanceChild taskInstance, Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup inferLookup, Microsoft.Build.BackEnd.Lookup executeLookup, System.Threading.CancellationToken cancellationToken)	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder, Microsoft.Build.BackEnd.Logging.TargetLoggingContext targetLoggingContext, Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup lookupForInference, Microsoft.Build.BackEnd.Lookup lookupForExecution)	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder, Microsoft.Build.BackEnd.BuildRequestEntry requestEntry, Microsoft.Build.BackEnd.Logging.ProjectLoggingContext projectLoggingContext, System.Threading.CancellationToken cancellationToken)	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetBuilder.ProcessTargetStack(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder)	C#
 	[Resuming Async Method]	
 	[External Code]	
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.InjectThread.AnonymousMethod__6_0()	C#
 	[External Code]	

```

**Comment by rokonec** [comment]
[like]  Roman Konecny reacted to your message:
________________________________

**Comment by SerendipitousTesselation** [comment]
Thank you for your analysis Jan.

I've only got the default Windows Defender on my machine though the pc is company managed. So, I tried it on a VM and couldn't reproduce the issue there.

I've also re-installed VS on my work PC which has got me a newer version (17.8) which  has fixed it for the PC too.

Go figure, I guess it really was the anti-virus.

**Comment by JanKrivanek** [comment]
@SerendipitousTesselation Thank you for getting back with your observations.
I'll be closing this now - but please feel free to reopen and add additional data/dumps if this reoccurs - this is not the tipical manifestation of the antivirus/antimalware collision (they usually hook on LoadLibrary(Ex) calls, rather then GetProcAddress)
