### ISSUE TITLE
[Broken Build]: integrated one loc build with the pipeline. The build fails with OneLocBuildClient.exe Error: 0 : System.ArgumentException: Invalid ref name: 'refs/pull/9149781/merge'.

### ISSUE THREAD

**Issue by madhurima09nath** [dotnet/msbuild#9526]
### Issue Description

Failure stack trace

OneLocBuildClient.exe Error: 0 : System.ArgumentException: Invalid ref name: 'refs/pull/9149781/merge'.
Parameter name: refName
   at OneLocBuildClient.Utils.GetBranchName(String refName) in C:\__w\1\s\src\OneLocBuildClient\Utils.cs:line 270
   at OneLocBuildClient.LocFileCheckin.<IsLocFilePresentAsync>d__19.MoveNext() in C:\__w\1\s\src\OneLocBuildClient\LocFileCheckin.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at OneLocBuildClient.LocFileCheckin.<PushLocFilesAsync>d__20.MoveNext() in C:\__w\1\s\src\OneLocBuildClient\LocFileCheckin.cs:line 390
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OneLocBuildClient.LocFileCheckin.<RunAsync>d__10.MoveNext() in C:\__w\1\s\src\OneLocBuildClient\LocFileCheckin.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OneLocBuildClient.LocController.<RunAsync>d__6.MoveNext() in C:\__w\1\s\src\OneLocBuildClient\LocController.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OneLocBuildClient.Program.Main(String[] args) in C:\__w\1\s\src\OneLocBuildClient\Program.cs:line 46
##[error]Process 'OneLocBuildClient.exe' exited with code '1'.

Any suggestions on how to fix this ?

### Steps to Reproduce

NA

### Expected Behavior

The build pipeline is broken because of failure in OneLocBuild.

### Actual Behavior

Build should pass.

**Comment by JanKrivanek** [comment]
@madhurima09nath - This isn't a MSBuild issue, but rather a OneLocBuild integration issue - please create IcM with "OneLocBuild" service

**Comment by rokonec** [comment]
We are closing this issue as we believe another issue has been created and forwarded to OneLocBuild team.
