### ISSUE TITLE
[Bug]: Placeholder syntax does not work as expected for extension manifests

### ISSUE THREAD

**Issue by techNIKtos** [dotnet/msbuild#9549]
### Issue Description

**case 1:**
Reference to a property, like this `$(PropertyName)`, that's defined in the VSIX project does not work for vsixmanifest.

Despite what is stated in this [document ](https://learn.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2022#placeholder-syntax-for-extension-manifests):
> To reference a property that's defined in the VSIX project, use the same syntax as you would in the project file itself, $(PropertyName).

But instead we get the same `$(PropertyName)` in the output without replacement. 

**Case 2:**
I also tried to reference an MSBuild target instead to get the desired behavior:
`<GettingStartedGuide>https://|%CurrentProject%;GetTest|</GettingStartedGuide>`

Here is the target:
`<Target Name="GetTest" Returns="www.somedomen.com/team/platform/doc/page.html" />`

It works, but not in the way we expect. This is what I get on the way out:
`<GettingStartedGuide>https://page.html<GettingStartedGuide>`
Only the last part of the link is shown, as if it is trying to return the file name instead. 
Note: the issue only occurs when there is a 'slash' character in the returned string.

**Case 3:**
Moreower, if the target returns the full link, including "https://", it lieads to an errror.
`<Target Name="GetTest" Returns="https://www.somedomen.com/team/platform/doc/page.html" />`

### Steps to Reproduce

[case1.zip](https://github.com/dotnet/msbuild/files/13682794/case1.zip)
[case2.zip](https://github.com/dotnet/msbuild/files/13682678/case2.zip)
[case3.zip](https://github.com/dotnet/msbuild/files/13682690/case3.zip)

1) Unzip attached samples and build each solution in debug configuration.
2) Check VSIX file in the output.

### Expected Behavior

VSIX should be built with the replacement of the placeholder with the correct values.

**case 1:**
The description in the output VSIX should be:
`<Description>Test description.</Description>`

**case 2:**
The GettingStartedGuide in the output VSIX should be:
`<GettingStartedGuide>https://www.somedomen.com/team/platform/doc/page.html</GettingStartedGuide>`

**case 3:**
The GettingStartedGuide in the output VSIX should be:
`<GettingStartedGuide>https://www.somedomen.com/team/platform/doc/page.html</GettingStartedGuide>`

### Actual Behavior

Placeholder syntax does not work as expected for extension manifests.

**case 1:**
The description in the output VSIX actually is:
`<Description>$(TestProp)</Description>`

**case 2:**
The GettingStartedGuide in the output VSIX actually is:
`<GettingStartedGuide>https://page.html</GettingStartedGuide>`

**case 3:**
VSIX is not being built and failed with an error:
> Error	MSB4018	The "DetokenizeVsixManifestSource" task failed unexpectedly.
> System.NotSupportedException: The given path's format is not supported.
>    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
>    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
>    at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
>    at Microsoft.VisualStudio.Sdk.BuildTasks.DetokenizeVsixManifestSource.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	VSIXProject1	C:\Users\nik-i\.nuget\packages\microsoft.vssdk.buildtools\17.0.5210-preview5\tools\VSSDK\Microsoft.VsSDK.targets	133		

### Analysis

case 1:
`$(PropertyName)` syntax does not work for some reason.

case 2 and 3:
Apparently, this is due to the fact that this string is recognized as the path to the file and therefore it tries to return the file name. I do not know if this is how it is intended, but we wonder if we can avoid this somehow.

**Comment by rainersigwald** [comment]
Team Triage: The VSSDK that controls VSIX packaging is part of Visual Studio, and not tracked here in MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.

**Comment by techNIKtos** [comment]
@rainersigwald , thank you for the help. Here is the [link to the ticket](https://developercommunity.visualstudio.com/t/Placeholder-syntax-does-not-work-as-expe/10542623?).

**Comment by rainersigwald** [comment]
Looks like it's routed to the right folks. Good luck!
