### ISSUE TITLE
[Flaky test] Microsoft.Build.UnitTests.BackEnd.TaskBuilder_Tests.CanceledTasksDoNotLogMSB4181

### ISSUE THREAD

**Issue by surayya-MS** [dotnet/msbuild#9638]
While working on https://github.com/dotnet/msbuild/pull/9621 I came across this flaky test. It doesn't flake that often. The last 4 failed builds have same error message and stack trace:
```
Shouldly.ShouldAssertException : isSubmissionComplated\r\n    should be\r\nTrue\r\n    but was\r\nFalse\r\n\r\nAdditional Info:\r\n    Waiting for that the build submission is completed failed in the timeout period 2000 ms.
```
```
at Microsoft.Build.UnitTests.BackEnd.TaskBuilder_Tests.CanceledTasksDoNotLogMSB4181() in D:\a\1\s\src\Build.UnitTests\BackEnd\TaskBuilder_Tests.cs:line 189
```

**Comment by surayya-MS** [comment]
https://github.com/dotnet/msbuild/issues/9298

**Comment by JaynieBai** [comment]
Still failed in latest build https://dev.azure.com/dnceng-public/public/_build/results?buildId=588018&view=ms.vss-test-web.build-test-results-tab&runId=14181820&resultId=104008

Error message
Shouldly.ShouldAssertException : isSubmissionComplated\r\n    should be\r\nTrue\r\n    but was\r\nFalse\r\n\r\nAdditional Info:\r\n    Waiting for that the build submission is completed failed in the timeout period 2000 ms.



Stack trace
   at Microsoft.Build.UnitTests.BackEnd.TaskBuilder_Tests.CanceledTasksDoNotLogMSB4181() in D:\a\1\s\src\Build.UnitTests\BackEnd\TaskBuilder_Tests.cs:line 189
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAtt

**Comment by f-alizada** [comment]
Another record of failed test: https://dev.azure.com/dnceng-public/public/_build/results?buildId=646890&view=ms.vss-test-web.build-test-results-tab
