### ISSUE TITLE
[Bug]: fakeroot breaks parallel msbuild tasks

### ISSUE THREAD

**Issue by nelsontkq** [dotnet/msbuild#9731]
### Describe the Bug

When using fakeroot on linux, it's not possible to build a .sln file in parallel.

#### Setup
```sh
dotnet new console -o test1
dotnet new console -o test2
dotnet new sln
dotnet sln add test1 test2
```

#### Test
```sh
dotnet build
// Build succeeded.
fakeroot -- dotnet build
// Build failed.
```

### Expected Behavior

Build succeeds

### Actual Behavior

Build fails

### Analysis

It can be worked around by forcing -maxcpucount:1, but this would mean patching every linux package that uses .net which isn't very sustainable.

#### Workaround
```sh
fakeroot -- dotnet msbuild -restore -consoleloggerparameters:Summary
// Failed
fakeroot -- dotnet msbuild -maxcpucount:1 -restore -consoleloggerparameters:Summary
// Succeeded
```

## MSBuild version
```
dotnet msbuild -version
MSBuild version 17.8.3+195e7f5a3 for .NET
```

## Dotnet info
```
dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.2fd734c4

Runtime Environment:
 OS Name:     solus
 OS Version:  4.5
 OS Platform: Linux
 RID:         solus.4.5-x64
 Base Path:   /usr/lib64/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.2fd734c4
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by nelsontkq** [comment]
Here's a binlog of this command failing:
```sh
 fakeroot -- dotnet msbuild -restore -consoleloggerparameters:Summary /bl:output.binlog
```
[output.zip](https://github.com/dotnet/msbuild/files/14251258/output.zip)

**Comment by YuliiaKovalova** [comment]
Hi @nelsontkq,

Thank you for opening the ticket.
I was able to repro it on Mac machine, the log is attached below.
[fakeroot_mac_failure log.txt](https://github.com/dotnet/msbuild/files/14278739/fakeroot_mac_failure.log.txt)

It fails on the next targets: _IsProjectRestoreSupported and _FilterRestoreGraphProjectInputItems, but there is a strange message displayed : `Done building target " " in project "test_fakeroot.sln" -- FAILED.: (TargetId:6)`
I will continue my investigation.

**Comment by nelsontkq** [comment]
Interestingly, for me that blank is `_FilterRestoreGraphProjectInputItems`
```
>Done building target "_FilterRestoreGraphProjectInputItems" in project "test.sln" -- FAILED.: (TargetId:6)
```
Here's the output with v:diag
[output.log](https://github.com/dotnet/msbuild/files/14290456/output.log)

At least there were only 4 relevant tasks which contain FAILED
```sh
nelson@nelson-solus ~/test $ cat output.log | grep FAILED
18:00:12.538     1>Done executing task "MSBuild" -- FAILED. (TaskId:5)
18:00:12.539     1>Done building target "_FilterRestoreGraphProjectInputItems" in project "test.sln" -- FAILED.: (TargetId:6)
18:00:12.540     1>Done Building Project "/home/nelson/test/test.sln" (Restore target(s)) -- FAILED.
18:00:12.566     3>Done Building Project "/home/nelson/test/test2/test2.csproj" (_IsProjectRestoreSupported target(s)) -- FAILED.
Build FAILED.
```

**Comment by YuliiaKovalova** [comment]
Hi @nelsontkq,

I was able to collect extra logs for [node-to-node communication](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Building-Testing-and-Debugging-on-Full-Framework-MSBuild.md#dumping-specific-logs) and parallel execution fails with

> System.AggregateException: One or more errors occurred. (Client connection (user id 501) was refused because it was not owned by the current user (id 0).)
>  ---> System.UnauthorizedAccessException: Client connection (user id 501) was refused because it was not owned by the current user (id 0).
>    at System.IO.Pipes.NamedPipeServerStream.HandleAcceptedSocket(Socket acceptedSocket)
>    at System.IO.Pipes.NamedPipeServerStream.<>c__DisplayClass25_0.<<WaitForConnectionAsync>g__WaitForConnectionAsyncCore|0>d.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
>    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc()

It looks like `fakeroot` is faking the uid of the app to 0, but not faking the uid reported as the owner of the socket.
MSBuild won't use it, because we try to avoid creating a pipe from an unelevated MSBuild to an elevated one.

It also explains why build works when you pass ` -m:1`
 
 We recommend you to open a bug in the fakeroot repo, there is nothing we can do from our side.
